### ISSUE TITLE
Curated content lists

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#108]
This would be a search, save, curate system, for adminstrator-type users:

(1) Search for a term to create a list, eg "counsel" or "bristol"

(2) Save the list

(3) Curate / remove sites that are not relevant

(4) Allow public access to the list at a url, eg /username/list/keyword

**Comment by dantheta** [comment]
A demo version of this feature is now on stage.blocked.org.uk.  Once you've searched, there's a dropdown button that reveals a form asking for a title and a user's name.  Once it's hoovered up the search results, it shows the list curation interface, along with a sharing link.  This is just a first pass, it can be made faster :)

**Comment by JimKillock** [comment]
Pam, would you like to try and feedback here?

**Comment by pamcowburn** [comment]
I think these lists work if individuals are sharing among themselves but if we are going to try and work with ISPs, their suppliers or journalists, it would be helpful if could save as CSV files that show URL, description and ISP who is blocking them.

**Comment by JimKillock** [comment]
I agree that end users may need a CSV, but compiling and checking the lists is much easier done within blocked. So perhaps what is needed is a CSV export option from the list, which should ideally also include the list URL?

**Comment by dantheta** [comment]
There's now an export button on the list view page, which downloads an Excel-compatible CSV with the list URL in the header section.

**Comment by JimKillock** [comment]
Checking how this works now we are on the live site

**Comment by dantheta** [comment]
Good point - now that we don't have authentication on the front, there isn't any notion of an admin user.  Shall we open list curation to all users?  We can have a hidden login page for admins, perhaps.

**Comment by JimKillock** [comment]
I would keep it restricted in some way. A hidden admin page sounds fine.

So long as the list pages are public, that’s fine.

**Comment by dantheta** [comment]
added a control panel login to https://www.blocked.org.uk/control

I'll send the username & password along.

**Comment by JimKillock** [comment]
I'm getting "Error
An error has occurred. Please try again later."

on save

**Comment by dantheta** [comment]
Ah - database credentials needed amending after the server move.  Fixed now, and tested.  Apologies!
