### ISSUE TITLE
report sites sent me to a non-blocked site

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#110]
On a first try, I was asked to check / report http://www.abovetopsecret.com at https://stage.blocked.org.uk/site/http://www.abovetopsecret.com

which was also marked as not blocked on the report page

**Comment by dantheta** [comment]
That site had one old block from TalkTalk strict, which is hidden on the new site.

One of the summary tables was built without the older networks (bt-moderate, bt-strict, talktalk strict) being excluded.  I've rebuilt the summary table using only the active ISPs, so there should be fewer of these.  Some no-longer-blocked sites may still be in the random set for a short while until the next rebuild of the summary.

A similar problem occurred with the full text index - that got fixed last week.
