### ISSUE TITLE
Screen porn from results

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#112]
When searching for keyword results, have a pre-ticked option to "screen likely pornographic sites". (Are there other things we should screen by default such as redirects?)

**Comment by pamcowburn** [comment]
'escort services'

**Comment by pamcowburn** [comment]
Redirects would also be helpful.

**Comment by dantheta** [comment]
I've experimentally excluded some obvious unambiguous porn & escort keywords, and will add in the UI elements shortly.

**Comment by dantheta** [comment]
The checkbox on the keyword search is now present.  The exclude wordlist is held in the API configuration, so it doesn't require code changes to eliminate further keywords.

**Comment by JimKillock** [comment]
Great. I'm not sure how to improve the exclusions list? Could it be listed from the admin pages perhaps? I'll add that as a further request so we can close this.
