### ISSUE TITLE
Legal blocks pages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#113]
Create a page for court order copyright blocks, another for PIPCU seizures.

**Comment by dantheta** [comment]
Are you thinking of an informational page with editable copy, or is there an interactive/data element to it?

**Comment by JimKillock** [comment]
The data element is just that it lists all the sites where a court order-style block has been detected. It could order these by date, or the active blocks first.

Some editable copy element would be helpful, so we can add links to explanations.

Some of the ISPs also link to a page detailing their court orders.

**Comment by dantheta** [comment]
Added http://stage.blocked.org.uk/legal-blocks (for copyright injunctions) and http://stage.blocked.org.uk/seized-domains.  We can hide the table on the latter page until we've collected some data for it.

The page copy can be edited by changing the Banner_Text and TextAreaOne|Two|Three template vars in the documents under browse.blocked.org.uk/feed in modx manager.  The CMS uses the Long Title field for the main heading on the page.

Changing the URLs is easy, if the ones I've picked aren't right

**Comment by JimKillock** [comment]
Thanks Dan. The copyright injunctions page is displaying no information for me either: but presumably you do have this information?

**Comment by dantheta** [comment]
legal blocks (copyright injunctions) are now shown

**Comment by JimKillock** [comment]
Thanks Dan. How are the copyright blocks selected? The list doesn't look very complete. We should make the list as comprehensive as we are able.

There is a case for testing these blocks more frequently as they are dropped periodically via instructions from the parties with the injunctions.

**Comment by dantheta** [comment]
Yep, it's only the most recent 25.  Do we want a full or paged list?

  I can also prioritize rechecking of copyright blocks.

**Comment by JimKillock** [comment]
I guess a paged list would be best (maybe with an option for a full list -- this could take advantage of a CSV export sometime as well).

Ideally we should group the blocks together by URL also, that is all the ISP blocks for a single URL consecutively.

The date column should be labelled "last check".

At a later date we could have an option to show historic (not current) blocks also.

**Comment by dantheta** [comment]
The date column is currently the date of first detection.  We can add a last check column too.

> Ideally we should group the blocks together by URL also, that is all the ISP blocks for a single URL consecutively.

I've got a great SQL query for this :)

**Comment by JimKillock** [comment]
Sounds great :) Yes, date of first detection is the more important date in fact.

**Comment by dantheta** [comment]
Paging links and titles  done.  Grouping in progress.

**Comment by JimKillock** [comment]
Thanks Dan. 

Looking in a bit more detail, some of the reports are URLs rather than domains. I think we can assume that they are not relevant, but the complicating factor would be that we should check for the domain to be present in the list.

Further question: the “first detected” date; is this the date of a first detection of a block; or the first detection of a court order notice? These may be different.

**Comment by JimKillock** [comment]
Moving refinements to a new ticket
