### ISSUE TITLE
Stats pages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#119]
Add a page giving an overview of the stats:

(1) would recreate the current "Alexa 100k" stats we have

(2) Could be a broad overview:

(a) Total domain tests run in UK, per ISP
(note why there are differences)
Tests, number of domain blocks, number of domain court order blocks 

(b) Total UK domain tests run, per TLD
(Number tested, blocks noted on each ISP)

**Comment by dantheta** [comment]
WIP: https://stage.blocked.org.uk/stats

**Comment by JimKillock** [comment]
This looks great so far :) I think the bar charts are easier to read / compare

**Comment by dantheta** [comment]
On 2017-08-14 11:49, JimKillock wrote:
> This looks great so far :) I think the bar charts are easier to read / 
> compare

Yeah :) I went to a data visualization workshop last week!

There's a small anomaly in the stacking, but that will be fixed 
imminently.

I'm crunching the data for TLD charts at the moment.

**Comment by dantheta** [comment]
The stats page is here: https://www.blocked.org.uk/stats

Is isn't linked from a menu at the moment.  Is it too busy?  Should it be split into more topic-focussed pages?

**Comment by JimKillock** [comment]
I think it’s good, and can be linked

A few of the results seem a bit odd, e.g.:

(1) What’s the blocked ac.uk domain? I can’t find it off the keyword search

(2) Why do EE, O2,  Vodafone seem to be blocking no co.uk websites?

There’s other things we ought to do e.g.

(3) Add in results for .com, .org and anything else we’ve processed in full

**Comment by dantheta** [comment]
The uk domain lists have started to run on the mobile probes (they didn't have the bandwidth before).

There's actually two ac.uk sites blocked now: 

```
            url             | network_name 
----------------------------+--------------
 http://www.oxfordgsb.ac.uk | Vodafone
 http://www.diasporas.ac.uk | EE
 http://www.diasporas.ac.uk | O2
 http://www.diasporas.ac.uk | Sky
(4 rows)

```

**Comment by dantheta** [comment]
.org is updating.
