### ISSUE TITLE
Descriptive [iinfo] (hover) links for filters

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#121]
Each filter we list, eg "BT light" should have a tooltip / information button that explains what the filter is, eg "This is the standard filter that BT encourages parents to use at sign up".

**Comment by JimKillock** [comment]
I'm going to bump this one up the priority list :) We should set up a page or pages in MODX for the tooltips I guess?

**Comment by dantheta** [comment]
Yep.  Probably chunks gathered together in an XML template would be easiest.  I'll create a category for the ISP description chunks to live in and add a resource which loads them as an XML doc.

**Comment by dantheta** [comment]
The chunks have been created in the Campaign Sites / Blocking / Network Descriptions category

**Comment by dantheta** [comment]
The tooltips are currently shown on the results page only.  We can add it to others though - feel free to reopen to have them added to other templates.
