### ISSUE TITLE
Sky blocking complaints may require customer account details

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#122]
Feedback by email:

Just noting that Sky require account details when you report a site
for unblocking - which might be something to consider for the site.

From Sky's reply:

> I wish to inform, I am unable to locate your account details with the
> information you have provided. In order to progress your future
> enquiries, please reply to this email with the following details:
> 
> 1. Sky Account Number or First line of address and Postcode
> 
> 2. First and last character of the password set on Sky Account. [This
> is not your email account password.]
> 
> Once we receive the security details, we will be able to access your
> account and assist you further

**Comment by JimKillock** [comment]
Thanks Dan. We can raise this directly with their policy team. It is another reason why we need to list the "recent reports" on a page -- and possibly break that down by ISP :)

**Comment by JimKillock** [comment]
Raised with policy team

**Comment by JimKillock** [comment]
They aren't enforcing this so I'm reckoning this to be closed. Note, it will help to alter the email as suggested in ticket #128
