### ISSUE TITLE
Don't check or suggest sites where probe is down

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#126]
Currently, we suggest sites to check where (a) the site block needs a recheck and (b) the ISP line cannot be checked because the probe is currently down eg at Virgin.

Furthermore the site suggests the user 'recheck' the block even tho this task cannot be completed.

This results in some time wasting for a volunteer / user.

Ideally these sites (one block, where probes aren't functioning) would be screened from the random sites.

**Comment by dantheta** [comment]
Excluded three and virginmedia from the random link generator.  The ISP status is held in the database, so it can be connected to passive monitoring for that isp's probes.
