### ISSUE TITLE
Add URL to email report

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#128]
Include a link to the blocked report in the email to ISPs, eg "You can view details including when the block was detected and who else appears to be blocking the site at: https://www.blocked.org.uk/site/http://www.site.org "

Also, maybe info on how it was generated:

"This email was sent from https://www.blocked.org.uk — you can learn more about how blocked reports are generated at https://www.blocked.org.uk/infoforisps "

– and add a page I can edit at /infoforisps

**Comment by dantheta** [comment]
Updated and live.
