### ISSUE TITLE
Add Piwik code

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#129]
Add Piwik tracking code to all blocked.org.uk pages

**Comment by JimKillock** [comment]
Site ID is 14

**Comment by JimKillock** [comment]
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://bug.openrightsgroup.org/piwik/" : "https://bug.openrightsgroup.org/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 14);
piwikTracker.disableCookies();
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="https://bug.openrightsgroup.org/piwik/piwik.php?idsite=14" style="border:0" alt="" /></p></noscript>

**Comment by dantheta** [comment]
Added piwik code.
