### ISSUE TITLE
Disallow reporting for select sites

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#134]
Add a feature to disallow reporting on the basis that an ISP believes the site to be correctly classified.

Record the date this is flagged in case we want to review this.

Record the categorisation, if known.

Additionally: find a list of known porn sites and add these to a "correctly classified" list.

As background, we've had this request from ISPs and today we've had someone report a porn site for review.

**Comment by JimKillock** [comment]
Note: this should apply to whole domains as previously discussed

**Comment by dantheta** [comment]
Added control panel for regexes / domain patterns that wil be blacklisted.
The frontend disables the "request unblock" button when it is showing results for a blacklisted site.  The adult/dead/broken feedback is still permitted.

If the user manipulates URLs to get the unblock form, even on a blacklisted site, they will get a message indicating that their unblock request has been rejected.  The wording is a bit plain at the moment, but can be reviewed here: 

https://github.com/dantheta/blocked-frontend-py/commit/4476f512a19fbc6cd0fd2521dd6426aee458f8ca

**Comment by JimKillock** [comment]
This looks very good. So any domain added will be blocked for all URL requests?

**Comment by JimKillock** [comment]
Just tested it and it clearly works that way, thank you!
