### ISSUE TITLE
Remove obvious abuse from the 'recent reports' list

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#135]
Allow admin user to hide any abusive reports (eg obvious porn), add the site to the 'disallowed' list, and keep the abusive reports out of any statistical analysis of ISP reporting.

**Comment by JimKillock** [comment]
We've a handful of these now. Perhaps we can remove reported sites that match to entries in the ban list?

**Comment by dantheta** [comment]
Have added a control panel that will allow ISP reports to be flagged as abuse.  These are hidden from the public reports page and will no longer be processed by the system.  Rolling out shortly.

**Comment by JimKillock** [comment]
Thanks Dan. Three amends / improvements:

(1) Flagged sites should display on the admin side as "flagged" once reported

(2) Flagging one URL / report should flag *all* reports for that URL

(3) The change should refresh  the page the user is on, e.g https://www.blocked.org.uk/control/ispreports?page=2 

rather than taking the user back to https://www.blocked.org.uk/control/ispreports

**Comment by dantheta** [comment]
(1) & (2) - that's how it should work already.  Something seems to be amiss ...

(3) - gah, paging.

**Comment by dantheta** [comment]
Yep, it was silently failing to apply the flag.  Should be fixed now.

**Comment by JimKillock** [comment]
Great work. Needs a means to "unflag" also (I just hit 'NordVPN' by accident)

**Comment by dantheta** [comment]
Unflag added.  I tested it on nordvpn, so that one's clear now.
