### ISSUE TITLE
View search term exclusion list at admin

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#136]
Have a page where the search term exclusion list can be viewed, and preferably also added to.

**Comment by edjw** [comment]
1. Do we do this now? 
2. If we don't do this now, do we still want to do this?
3. Should we close this ticket? Or should we re-prioritise it?

**Comment by dantheta** [comment]
Duplicated by linked ticket.  The other one is more detailed, so I'll close this one.
