### ISSUE TITLE
Hide flagged sites

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#140]
Flagged sites seem to appear as "Unblock requested" rather than "flagged"

See https://www.blocked.org.uk/site/http://www.ocardo.co.uk

They should probably be hidden, or viewable from a special page.

**Comment by dantheta** [comment]
I think hidden from search results, but findable through URL lookup.

I've removed the flagged sites from the search index, we just need a small job that is triggered when a site is flagged.

**Comment by dantheta** [comment]
The button title now changes depending on whether the site is flagged or reported for unblocking.
