### ISSUE TITLE
Add line status on front end

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#142]
New "Line stats and status" page

Have a line status page to help users if they are not able to get results from certain probes.

This could be at https://www.blocked.org.uk/stats/probes

This could be a table stating

* Line / Status 

Status could include:

* Line currently off; Probe down; Filtering malfunctioning;

Stats

* Per ISP line, per month, bar graph: days filter on; days filter off
* Total filter up / down time per ISP probe

Per ISP unfiltered line: days when filters detected:
* per month, bar graph: days filter on; days filter off
* Total filter up / down time per ISP probe

**Comment by JimKillock** [comment]
Dan, I'm moving this up the pile so that we can point TalkTalk and Ofcom to stats regarding TT's filter malfunctions.

**Comment by dantheta** [comment]
The filter up & down time isn't data that we've currently got available historically.  The last seen timestamp is the most readily available stat.  We can add some extra telemetry to the probe so that self-test failures are recorded.

**Comment by JimKillock** [comment]
OK, that makes sense. The TT info could be generally useful, where we know users have chosen a setting, and it gets changed without warning :)

**Comment by JimKillock** [comment]
Thanks for the changes so far Dan. Will the status reports be able to say "unfiltered" and show the line as expected "filtered" or similar? The results will need to show that TT filtering is expected and not present, etc

**Comment by JimKillock** [comment]
Maybe we could add a column saying: "Filtering" with results "On" or "Off" and make the names clearer, eg:

* Virgin Media default filter AAISP
* Virgin Media default filter line 2
* TT Kidsafe AAISP
* TT line 2 variable filtering
* EE filtered
* O2 filtered
* PlusNet filtered AAISP
* PlusNet filtered line 2
etc

**Comment by JimKillock** [comment]
I'm going to close this issue as the next detailed changes are now in #247
