### ISSUE TITLE
Use multipage format for search and lists

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#149]
On the search and lists pages, eg 

https://www.blocked.org.uk/list/Birmingham

or 

https://www.blocked.org.uk/sites/birmingham?exclude_adult=1

use the numeric style of pagination, with a link to the first and last pages as used on the court order blocks pages

**Comment by dantheta** [comment]
Lists page is done.

**Comment by dantheta** [comment]
The page count on very large categories can drift out of sync over time to due cached statistics; I'll keep an eye on it.
