### ISSUE TITLE
Copy - What is "Internet Matters" in About section?

### ISSUE THREAD

**Issue by SimonStJG** [openrightsgroup/blocked-org-uk#150]
About -> What does ORG want to happen?

To me, the following sentence doesn't make sense - what is "Internet Matters" here?

We want to make it easier to get sites unblocked. We think one of the ways that mobile phone companies, ISPs and Internet Matters can do this is by promoting the Blocked tool, which is the only way that someone can instantly check if a website is blocked.

**Comment by JimKillock** [comment]
Fixed at CMS, may take a while to update on the front end
