### ISSUE TITLE
Licence agreement

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#159]
We need to state that all submissions, report info etc is subject to X licence conditions (same as our data and copyright licence).

This should be stated when people are given email confirmations to submit reports in particular.

Also on the report submission page (underneath text box)

We also need to replace the /licence page

**Comment by JimKillock** [comment]
I've duplicated the old licence page and moved into the feed area

**Comment by dantheta** [comment]
I've added it to the frontend.  I've given the list of software components a bit of an update too.
