### ISSUE TITLE
Run your own probe page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#160]
Page describing how to run a probe, download software etc. Could be on the Wiki rather than at blocked.org.uk

**Comment by JimKillock** [comment]
I've added text at https://browse.blocked.org.uk/feed/run-your-own-probe.xml

**Comment by dantheta** [comment]
Page is live, and can be linked from the support page.  URL is: https://www.blocked.org.uk/run-your-own-probe
