### ISSUE TITLE
Options on "Unblock another site" page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#161]
When landing on the thank you / "Unblock another site" page, after submitting a unblocking request, the user should be given an option to check something else, eg:

 REQUEST UNBLOCK / VISIT SITE / TRY ANOTHER SITE

**Comment by dantheta** [comment]
For unblock requests, it already does this, providing email verification is not required.  This functionality is not yet enabled on the thanks page after flagging a site.  I'll get that added now.

**Comment by JimKillock** [comment]
Just checked, via a random site from the front page, and I'm not getting a 'try another site' option.

**Comment by dantheta** [comment]
The route marker is in place for the frontpage random links.

**Comment by dantheta** [comment]
Fixed now.

**Comment by JimKillock** [comment]
Not working for me.

I tried reporting a random site, and got to the thank you page, but did not get a "try another site" link.

TBH it can just be on all results pages?

**Comment by JimKillock** [comment]
(still not working for me.)

**Comment by JimKillock** [comment]
Placing this request here: on cycling through a "chess" search, I needed to try another site in my search, while on a results page, but did not have a link to "try another site".

If I report the site as adult, I do cycle back to the results, which is great.

**Comment by dantheta** [comment]
OK, think I got it this time.

**Comment by JimKillock** [comment]
Great, yes working for me. The random results are 90% irrelevant now so it is getting a bit hard to test!
