### ISSUE TITLE
Allow user to cycle through a search list

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#162]
When requesting an unblock for a site following a search, the user should be presented with the next result from the search result, and continue to cycle through the search results, rather than being given a "random site" to check at the "thank you" page.

This would also apply when navigating from a "saved list".

If this is troublesome, it can probably wait, but would make the site a lot more usable i think

In this case. the "thank you" page would present these options:

REQUEST UNBLOCK /  VISIT SITE  
SEE NEXT SEARCH REPORT / BACK TO RESULTS

**Comment by dantheta** [comment]
keyword search and category search results already show further entries from the same source on the thanks page.  

At the moment, the saved lists are held in a database by the website frontend; they should be moved into the middleware, where we'll be able to join against the probe results and filter them based on whether they're still blocked or have been reported.  Then we'll be able to do forward navigation without randomly selecting sites that aren't blocked any more or sites which have already been reported.

**Comment by dantheta** [comment]
I've made some fixes to onward navigation that should improve the flow.  Also fixed is the message at the top of the page when an onward site is available: it displays a suitable message depending on whether the last action was to flag a site or report it for unblocking.

**Comment by JimKillock** [comment]
Does this also work for saved "lists"? It should I feel.

**Comment by dantheta** [comment]
Yep, that's enabled now.  In the short term, the random selection from the list doesn't know if the site has been unblocked or not.  This will change when the lists are stored in the backend,

**Comment by dantheta** [comment]
Left a reminder here: openrightsgroup/cmp-issues/issues/173
