### ISSUE TITLE
Lists and blocking info

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#163]
Add to user created lists

(1) blocked / unblocked info 

(2) reported / unreported

(3) Link at top saying "Report these sites to ISPs"

Ensure behaviour of user created lists is to retain all sites whether blocked or unblocked

**Comment by dantheta** [comment]
1 & 2 have been taken care of in other tickets.  I think (3) has been taken care of as well.

**Comment by JimKillock** [comment]
(1) and (2) are done, looks great.

On (3) I think the lists need an "unblock this site" link, at the far right, after  "view site report"

**Comment by JimKillock** [comment]
Ping on this change Dan, it'd be good to clear this one out of the 'review' pile!
