### ISSUE TITLE
Better sources of URLs for front page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#165]
Currently, the random sites are predominantly guns and alcohol. Around 15-20% seem to be in error. A higher percentage would help people get involved with correction.

Base the examples on user saved lists.

This would allow our local groups and activists to save lists of material that we believe needs review.

If some of the lists end up full of junk, we might need to 'opt out' lists from this.

**Comment by tonynaggs** [comment]
Maybe we can do better at prioritising English language sites? Even with the help of Google translate I'm not necessarily able to quickly distinguish a Japanese blogging site from an erotica site.

**Comment by JimKillock** [comment]
@tonynaggs We should overcome the language issue by using our user generated lists

**Comment by JimKillock** [comment]
@dantheta I think there are sufficiently large lists to make this a goer now. We might want to add an admin feature to select the lists for the front page in the admin pages
