### ISSUE TITLE
Capitalisation leading to duplicate entries

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#170]
In (sub) domain entries particularly, capitals should not lead to duplicates.

With the list of legal blocks, these have come to the top of the list up recently:

http://Couchtuner.me
http://Gostream.is

and this, previously reported:
Http://thepiratebay.org

**Comment by dantheta** [comment]
No new duplicates can go into the system now.  I'll need to spend a bit of time cleaning up the existing data, which is one of the tasks in #138 .  I'll close this one for now.
