### ISSUE TITLE
more categories for yes this should be child-blocked

### ISSUE THREAD

**Issue by tonynaggs** [openrightsgroup/blocked-org-uk#171]

**Comment by tonynaggs** [comment]
When classifying a web site it would be good to have more categories, it seems wrong to tag everything I think should be blocked as porn. And is unhelpful if someone wants to review my classifications.
Suggestions:  non-porn but sex related, cannabis/drug supplies/culture, anarchist / bomb making kinds of stuff, eating disorder fetishism.

**Comment by tonynaggs** [comment]
I guess also gambing, tobacco / alcohol brands, violence/gore. I'm sure there are a few more.

**Comment by JimKillock** [comment]
https://www.blocked.org.uk/stats has the categories the ISPs are using, so maybe we should use that.

Alcohol is problematic of course. I agree "brands" is the right categorisation as it excludes pubs, vineyards and restaurants.

**Comment by JimKillock** [comment]
See also #182

**Comment by JimKillock** [comment]
Categories look good. I think with Alcohol, we should change this to "Alcohol brand promotion" and have a note that we do not include vineyards, pubs or restaurants as suitable for blocking.

**Comment by JimKillock** [comment]
For "pornography" we could say "Pornography and adult sexual content"

**Comment by dantheta** [comment]
Those are done.
