### ISSUE TITLE
Control page fixes

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#175]
1 Top link goes to /admin ("Blocked.org.uk Admin")

2 Some of the list appear to be listed twice (they may not be duplicates, as they have the same number of sites listed)

**Comment by dantheta** [comment]
They were lists created with the same names (missing unique constraint).  This has been fixed now, and the duplicates have been suffixed to allow them to be reviewed and deleted if necessary.
