### ISSUE TITLE
ISP response statistics

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#179]
Display numbers for unblock requests per ISP:

* Total requests made
* Total / percentage unblocked following request (based on 'single ISP requests' only [1]
* Response time in days (based on date the email is sent, not the date the request is submitted)  (based on 'single ISP requests' only [1]

[1] Many requests that go to multiple ISPs will result in an unblock across several ISPs, so responses reflect the most responsive ISP, and we cannot tell which is responsible

**Comment by dantheta** [comment]
A multi-isp request is duplicated into a request per-isp at the time of submission, so they are measurable individually.

**Comment by JimKillock** [comment]
For sure, but they don’t mean the same thing. For instance, a request to BT and Virgin may be processed by BT resulting in Symantec removing a site from blocks at Virgin. Thus it is unfairly positive in this example to calculate an unblock at Virgin as being a “positive response” as it may represent no response at all.

**Comment by dantheta** [comment]
Added as a short table (with expander) to the reported sites page.

**Comment by JimKillock** [comment]
Thanks Dan. Elsewhere I'd thought about:

* Total number of reports
* Total number of sites reported to ISPs
* Number of sites unblocked
* Percentage unblocked following report

I think we need at least number of reports plus total number of sites reported, as it looks currently like a very low number of sites get unblocked (about 25%) – whereas it is probably more like 50-60%.

Currently I'm guessing "reports sent" could sometimes mean two to five reports sent re one website.

**Comment by dantheta** [comment]
Perhaps we can move the ISP responsiveness figures (using the current formula) to the ISP stats pages, so that users can see all of the figures related to an ISP in one place.  

For the reported-sites page, we can use stats across all of the reports which reflects better the effectiveness of the system as a whole.

**Comment by JimKillock** [comment]
Yes to moving the per-ISP stats but I'd suggest to a new page; maybe stats/reporting

I think we want to emphasise who is good / bad so we'd usually need a user to compare all ISPs at once, across each type of statistic.

For this page we can just present:

* Total block reports made
* Total blocks removed

(ie, two comparable stats, so that we don't make the performance look worse or better than it is).

**Comment by JimKillock** [comment]
Tweaks for the stats at https://www.blocked.org.uk/reported-sites :

(1) Add after "Reports Sent" "Total sites" "Sites unique to ISP"

(2) Amend "Sites Unblocked" to "Sites verified as unblocked by this ISP"

(3) Add "All sites unblocked at this ISP"

(4) Add text field for the methodology so we can explain how and why we present these stats this way.

**Comment by dantheta** [comment]
The stats block has been moved off to the statistics page now.
