### ISSUE TITLE
Epic: Create news page using "articles" blogging engine

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/blocked-org-uk#18]
ORG's main site uses the MODX extra [Articles](http://rtfm.modx.com/extras/revo/articles) for the local groups news pages (e.g. https://sheffield.openrightsgroup.org/). We should try to integrate "Articles" onto this news page so that the blogging engine is uniform across all ORG blogs. This would also allow us to display blocked.org.uk news posts on the main page and in our main RSS fees.

We could launch version 2.0 without this page so I'm flagging it as an enhancement.

**Comment by JimKillock** [comment]
I think we can close this (replace it with a feed instead)
