### ISSUE TITLE
Skip "your details" page when user confirmed

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#184]
There is no need to go through this page once a user has confirmed their details.

The owner / user options could be put onto the submit report page if we wanted.

This would speed the process up

**Comment by dantheta** [comment]
A name/email summary has been added to the second page, with a link to change the details.  If the user is taking the faster path through, then it skips the user/owner/someone-who-cares checkboxes.  We can move those to the second page if we want to make sure they're filled in.

**Comment by JimKillock** [comment]
Looks good, thanks Dan
