### ISSUE TITLE
Previously blocked or reported results appearing in search

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#189]
When searching for 'chess' sites, and cycling through sites to report them, a previously reported, now unblocked site came up for reporting:

https://www.blocked.org.uk/site/http://chess-links.org

Another result came up that was blocked but already queued for reporting:

https://www.blocked.org.uk/site/http://chessgames.com

**Comment by dantheta** [comment]
We'd previously removed urls from the search index when they were unblocked - I've updated the reporting code to remove urls when they are flagged and/or submitted for unblocking.  There were a few stragglers left in the search index from before the code was written.

Second-hand data is always problematic ...

**Comment by JimKillock** [comment]
I'm still getting this behaviour, seemingly including sites I'd just reported. See also #201

**Comment by JimKillock** [comment]
This is good enough for launch, so I am changing the tag in case you want to leave it till next week.

**Comment by dantheta** [comment]
I don't think we should have seen too many more occurrences of  this.  Sites are removed from the search index within half an hour of being reported.
