### ISSUE TITLE
Contact page - content review

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/blocked-org-uk#19]
This page is a duplicate of the main contact page for ORG at https://www.openrightsgroup.org/contact. It would be best if we could embed this page on blocked.org.uk but keep our site header and navigation. Then if ORG's contact details are updated we don't have to change them in two places.

We need to find out if this is possible in MODX and perhaps discuss with @JimKillock and @mkillock how best to achieve this in practice.

**Comment by edjw** [comment]
Duplicated contact details from Get Involved and added basic contact details for ORG office

https://www.blocked.org.uk/contact

**Comment by JimKillock** [comment]
Suggest the new site simply directs people to openrightsgroup.org/contact

**Comment by dantheta** [comment]
Linked as suggested.  We can port the contents of the blocked /contact page if required.
