### ISSUE TITLE
Check mobile contact emails

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#207]
As we aren't getting responses from O2 and EE, can you check that the emails are going to the contact addresses listed here:

http://www.bbfc.co.uk/about-bbfc/links#mobile

**Comment by JimKillock** [comment]
I've filed four of the complaints EE / O2 haven't responded to the to BBFC as an 'appeal' to see if that prods them into action

**Comment by dantheta** [comment]
We had: 
O2:  shieldav@o2.co.uk 
Vodafone: ukmediarelations@vodafone.com

The BBFC page lists:

imescalations@o2.com
Contentclassification@vodafone.com

Vodafone were very responsive on the media address though.

The EE address we're using matches the one on the BBFC site.

**Comment by JimKillock** [comment]
Thanks Dan. We should use as advertised, as we want all complaints dealt with properly, nit just ours.

**Comment by dantheta** [comment]
Updated.

**Comment by gwire** [comment]
We've received an email from O2 stating the correct address:

> Can you amend the email address that you send website reviews through to for O2.
>
> It should be ShieldAV@O2.com
>
> The current address you are using of IMEscalations@o2.com is incorrect and is slowing down the process of dealing with reviews

**Comment by dantheta** [comment]
This has been updated now.
