### ISSUE TITLE
Two admin levels plus user accounts

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#209]
Create two levels for logged in users:

* basic, that can create and edit saved lists, 
* admin, that has all the extra abilities, to delete lists, assign to front page etc

Create user accounts to assign to the permission levels

**Comment by JimKillock** [comment]
Also: allow users to view lists of their own blocked reports

**Comment by dantheta** [comment]
Multiple user accounts feature is live now - the previous admin user account is still valid, and addition users can be created by an admin using the users tab in the control panel.  Just doing the privilege separation stuff now.

**Comment by dantheta** [comment]
That's live now.  The "moderator" user role is able to create & manage URL lists.

The user's admin level is shown in a little badge in the top left when they are on the main site.
