### ISSUE TITLE
Add statistic to front page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#211]
N domains and URLs checked totals, N blocks detected

**Comment by JimKillock** [comment]
Add N blocks detected as the absolute number (eg 1 million of the 21 million)

**Comment by dantheta** [comment]
Updated.  Might look at justifying the large paragraph text to the left.

**Comment by dantheta** [comment]
Or putting the stats in a gray panel?

**Comment by JimKillock** [comment]
This is fine for now, thank you! We will need to re-order the front page a bit some point, so we can close.
