### ISSUE TITLE
Try another site link sometimes gives 500 error

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#218]
When a search or category has only one result, the "try another site" (/next) link errors a 500 error. This also happens when using the same button from the /thanks page. The link should be removed from that page, since it has already failed to select a follow-on site.

**Comment by gwire** [comment]
Something other than an error should happen when someone visits "/next" on its own, also.

**Comment by dantheta** [comment]
Indeed - when the URL works, it always emits a redirect, so I hadn't intended it to be part of the public interface.  It should fall back on pulling a random URL from the public lists if there's no saved route information.
