### ISSUE TITLE
Logged in and not logged in versions are different

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#220]
The not-logged in version has content that is maybe 1-2 days old

**Comment by dantheta** [comment]
The frontend caches the remote loaded content for logged-out users.  When logged in, admin users always see the latest version.  Saying that, it should only cache that content for a few hours, so something is going amiss there.

**Comment by dantheta** [comment]
I've hand-cleared the cache, so the newest content should be visible for all users.

**Comment by dantheta** [comment]
We could also have a "clear cached content" button in the admin panel, in case there's a typo in the CMS content that we want cleared quickly.

**Comment by JimKillock** [comment]
Sounds a good idea :)

**Comment by dantheta** [comment]
Added admin panel function.
