### ISSUE TITLE
Find .uk suspended domains

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#221]
We should be able to find .uk domain suspensions at Nominet. See: https://www.infosecurity-magazine.com/news/suspended-uk-domains-double-in-a/

We may also need to find different suspension pages, eg:

DEFRA – Veterinary Medicines Directorate; Metropolitan Police – Fraud and Linked Crime Online (FALCON); the National Crime Agency (NCA); Medicines and Healthcare Products Regulatory Agency (MHRA); Trading Standards; National Fraud Intelligence Bureau (NFIB); and the Police Intellectual Property Crime Unit (PIPCU).

I will put in FoI requests; Dan can you think about why we haven't noticed the suspension pages as yet>

**Comment by dantheta** [comment]
We've picked up a few - https://www.blocked.org.uk/sites/pipcu 

The probe rulesets don't cover the domain seizures at the moment - they don't vary by ISP.  Also, during the larger scale URL testing we were only collecting page metadata for sites that had been matched against copyright/parental control.  The page data was being collected for the keyword search index, and we didn't have a use for page content of sites that didn't have any blocks registered against them.

**Comment by JimKillock** [comment]
OK, not a problem. Are we able to detect them now, or to start looking for them?

**Comment by dantheta** [comment]
Yep - I've got a match pattern for pipcu, and as we find others we can include them too.  It might be good to refactor the rules file a bit so that we can have a global pattern list as well as the per-ISP ones.

**Comment by JimKillock** [comment]
yes, for suspension on one line means it does not need testing elsewhere. The main thing is that we try to record the suspension page.

For PIPCU we could try finding domains that resolve to their IP address  83.138.166.114 (see http://83.138.166.114 ) and then if we like double testing them … except their server isn't responding …

**Comment by JimKillock** [comment]
See also https://wiki.openrightsgroup.org/wiki/Police_Intellectual_Property_Crime_Unit#Domain_pointing

**Comment by JimKillock** [comment]
Closing this as we got as far as is likely currently.
