### ISSUE TITLE
Copy changes: making complaints to ISPs clearer

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#223]
At https://www.blocked.org.uk/unblock 

https://www.blocked.org.uk/unblock2

"Request a site be unblocked" » "Request ISPs remove this site from filters"

Add: "This request will be sent to all ISPs to remove this site from their content filters."

"Please explain why this site should be unblocked" Add
"Your email will be sent to [ISP], [ISP]."

Thank you page: "Your unblock request was successfully submitted and will be sent to the appropriate ISPs."

Add "Please check your email for a copy of the email sent and any responses from them."

**Comment by dantheta** [comment]
Updated.  The unblock thanks text is stored in the unblockThanks chunk in modX, in case it needs any more changes.

**Comment by cmlb1879** [comment]
Can we (on https://www.blocked.org.uk/unblock) add in, under the link, above the Your details "Use this form to send ISPs an e-mail, asking them to remove this site from their filter block list"

**Comment by JimKillock** [comment]
Looks like this is all done
