### ISSUE TITLE
The Legal Blocks page could use a simple description, something like "These are lawful blocks that have been ordered by the Government"

### ISSUE THREAD

**Issue by cmlb1879** [openrightsgroup/blocked-org-uk#225]
The Legal Blocks page could use a simple description, something like "These are lawful blocks that have been ordered by the Government"

**Comment by dantheta** [comment]
Do we need to make a distinction between the Government and the courts?

**Comment by JimKillock** [comment]
I've edited this in the CMS so it has a reasonable description of what is going on. Thanks for the clear ache facility also Dan!
