### ISSUE TITLE
Card for social media

### ISSUE THREAD

**Issue by cmlb1879** [openrightsgroup/blocked-org-uk#226]
Add an image to pull through in social media links

**Comment by JimKillock** [comment]
Suggest that we do this via MODX, ie assign images and URLs from the template variables on the pages.

**Comment by JimKillock** [comment]
@cmlb1879 Is this fixed, or is the problem specific pages other than the front page?

**Comment by cmlb1879** [comment]
@JimKillock the validator for twitter says it can't find a card still

**Comment by dantheta** [comment]
I don't think there are any OG template vars assigned to the feed resources or template in ModX yet.  Once they've been added there I can pull them into the main template.  In the meantime I can add some basic metadata to the results page template.

**Comment by dantheta** [comment]
I've added the placeholder OG/Twitter stuff *just to the results pages* (for sharing), and tested with the validator.

**Comment by JimKillock** [comment]
@cmlb1879 Can you test and review this?

**Comment by JimKillock** [comment]
@dantheta For results pages, in priority order:
* if there is a court order, it should say: "Site blocked by court orders at …"
* otherwise, if there there is a user review, this should be the OG description content. 
* otherwise, as a last resort, a list saying "site blocked by filters at … " or "No filter blocks currently detected."

**Comment by cmlb1879** [comment]
It is still coming up as no card found: https://cards-dev.twitter.com/validator

**Comment by JimKillock** [comment]
@cmlb1879 What URL did you test on the validator?

**Comment by cmlb1879** [comment]
@JimKillock https://www.blocked.org.uk/

**Comment by JimKillock** [comment]
@cmlb1879 I think @dantheta has only done the *results* pages so far, eg: https://www.blocked.org.uk/site/http://www.hobs4hope.org

**Comment by cmlb1879** [comment]
Cool - that's working! that will be really helpful!

**Comment by JimKillock** [comment]
I think we need default values for all pages. Preferably we should be able to overwrite these in MODX, but a default would make life easier.

**Comment by dantheta** [comment]
Basic card metadata is now present on all pages.  It uses the page title for now, with a generic description.  It can be overridden for individual pages on the template side - I'll look into ModX for it.

We can get the generic description from ModX.  I'll add it to the chunks in the usual place (chunk name is browseOgDescription).
