### ISSUE TITLE
More probes and data

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#227]
Add extra probes for:

* EE
* Increase bandwidth on O2
* TT new line

**Comment by JimKillock** [comment]
EE is ordered and working, 50gb pcm line, so lots of capacity.

TT landline is ordered and in progress for mid December.

O2 is upped to 3gb but we can increase it further.

**Comment by JimKillock** [comment]
I will also see about an O2 4G data SIM, they're much bigger data contracts

**Comment by JimKillock** [comment]
Looking at the mobile packages, we can upgrade to 4G packages for O2, Three and Vodafone, with data from 20-50gb a month. Three IIRC has to be a phone contract. O2 and Vodafone have confirmed that parental controls are present on their data lines.

**Comment by JimKillock** [comment]
O2 and Three now on their way.

**Comment by JimKillock** [comment]
Vodafone is the last one; this is in progress so hopefully this will be sorted out next week.

**Comment by JimKillock** [comment]
Vodafone line is bought, I will collect tomorrow along with a replacement EE wifi unit.

**Comment by JimKillock** [comment]
Vodafone line and probe is now up for testing; EE replacement wifi hub should be delivered tomorrow.

**Comment by JimKillock** [comment]
All operational except for TT, due in 10 days

**Comment by JimKillock** [comment]
TT install is Thursday, probe is on its way.

**Comment by JimKillock** [comment]
TT install is delayed until 2 Jan

**Comment by JimKillock** [comment]
PlusNet ordered also

**Comment by JimKillock** [comment]
PlusNet due 23 Jan, RPi on its way.

**Comment by JimKillock** [comment]
TT install complete

**Comment by JimKillock** [comment]
PlusNet install complete

**Comment by dantheta** [comment]
The new plusnet line definitely has parental filtering active.  I think it's the first time we've seen it working on plusnet!
