### ISSUE TITLE
General clean up of sites to unblock needed

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#234]
This is a general feel from trying to make reports: I quickly got a lot of data that seemed not very relevant or worth reporting. 

This may be because obvious sites are already reported, or it may be poor luck; or perhaps the user lists themselves are not especially clean.

**Comment by dantheta** [comment]
This might have been lessened now that we've sorted the frontpage list cycling problem (in that it was drawing primarily from the old dmoz report candidates instead of the curated lists).    If a site appears on a list, it will be linked from the site result page.

**Comment by JimKillock** [comment]
Seems better now, so closing
