### ISSUE TITLE
Add source of URL

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#235]
For debugging and interest purposes:

On the front page, and from the thank you page, add:

"Website selected from user list [link][Name][/link]"

This will help us locate any lists with bad data.

**Comment by JimKillock** [comment]
(It's also helpful for people navigating from a list, and for discovery of the lists)

**Comment by JimKillock** [comment]
Looks good to me :)

**Comment by JimKillock** [comment]
Can we add this to the thank you and site report page also:

https://www.blocked.org.uk/site/http://www.days-calculator.com 

Perhaps: "This website is listed on user list [link][Name][/link]"

**Comment by JimKillock** [comment]
Trying to cycle through the sites just now I am getting mainly weapons and alcohol. I'm suspecting that we either have some rogue lists, or the data isn't derived from the lists. We need to display the list source on the thank you page to debug / locate and clean up the source material.

**Comment by dantheta** [comment]
I've moved the link to the lower-right section, underneat the permalink.  It's displayed on any site that appears on a public list, even if the site page isn't showing the thankyou message.
