### ISSUE TITLE
Saved lists page improvements

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#239]
Add new information columns on saved lists page:

* Number of sites
* Number of reports made
* Number of sites blocked
* Number of sites unblocked

**Comment by dantheta** [comment]
Is this for the adminitrator's list of lists page, the public one or both?

**Comment by JimKillock** [comment]
This is for the public page

**Comment by JimKillock** [comment]
Actually, this would also be handy on the admin page. So both.
