### ISSUE TITLE
Remove public block pages from court order block lists

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#242]
The block pages themselves, eg:

* https://www.blocked.org.uk/site/http://assets.virginmedia.com/site-blocked.html 
* https://www.blocked.org.uk/site/http://www.ukispcourtorders.co.uk

Should be excluded from the court order lists; (but as noted in #187 the links should be available in the site reports).

**Comment by dantheta** [comment]
Updated.
