### ISSUE TITLE
Random sites (in report cycle) not from lists

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#244]
After making the first report, the dataset for the random sites seems to be the old data (ie, mostly alcohol / gambling / guns).

(This is data presented on the "thank you" page / site report page)

Can you check and ensure we are drawing this from the saved lists?

**Comment by dantheta** [comment]
Yep, I'd realized that very late last night :) the front page sets the wrong route marker, so the random site of last resort routine kicks in.

On 27 November 2017 12:03:02 GMT+00:00, JimKillock <notifications@github.com> wrote:
>After making the first report, the dataset for the random sites seems
>to be the old data (ie, mostly alcohol / gambling / guns).
>
>Can you check and ensure we are drawing this from the saved lists?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
