### ISSUE TITLE
General error-ness

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#245]
Something odd is going on, I'm getting a lot of odd errors, eg 

"Method Not Allowed

The method is not allowed for the requested URL."

This is happening every 4-5 page visits at different URLs. Generally a reload, or revisiting the link, resolves it.

**Comment by JimKillock** [comment]
Maybe related, a few of the submits (eg sending report to ISP, final step) for have sent me off to netblocked.eu

**Comment by dantheta** [comment]
That sounds really odd.  (the site-switching).  I've changed some apache configuration which should further separate the two sites (hopefully).

**Comment by JimKillock** [comment]
I think you've fixed whatever was causing these issues. So closing this.
