### ISSUE TITLE
Court order information

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#253]
From #139,

(1)  Display Court Order information on the Court Order page:
(a) Order page blocks by Injunction / request, 
(b) then by URL group

(3) On the URL / domain report:
(a) Link back to the injunction and URL group
(b) Per ISP,  link to the relevant court order on wiki.451 
(c) Per ISP / URL, we will link to an example 451 error

**Comment by dantheta** [comment]
1 a&b are done.  Grouping inside the table is a little strange, let me know what you thing.

When there's no group or judgment title, the  header row is not shown.

**Comment by JimKillock** [comment]
Thanks Dan, looks great :)

On ordering the court orders, this should:

(1) List by (reverse) date
(2) Display date in grey bar
(3) Display the description text under the title within the grey bar

With non-assigned sites:

(1) Have a grey bar title saying: URLs not yet identified with a legal decision to block

**Comment by dantheta** [comment]
For (3), is the description text the affected sites description from the editor screen?

**Comment by JimKillock** [comment]
Yes, that's the one.

**Comment by dantheta** [comment]
1-3 from the amendments are done.  Working on (3) from the top of the ticket.

**Comment by JimKillock** [comment]
Thanks Dan. A couple more minor additions, for the grey bar:

(1) link to the Wiki page; 
(2)  link to Judgment if available.

and for general behaviour of the page

(3) List all judgments, whether they include blocked URLs or not. Where no site or IP address is detected, state "No sites or IP addresses currently detected."

**Comment by JimKillock** [comment]
Some small changes here that are worth doing so we can close this ticket.

**Comment by dantheta** [comment]
wiki and judgment links are done

**Comment by dantheta** [comment]
We don't have a linkable page for the URL group yet, that will follow #301

**Comment by JimKillock** [comment]
The only bit of this that needs doing now is:

(3) List all judgments, whether they include blocked URLs or not. Where no site or IP address is detected, state "No sites or IP addresses currently detected."

The links back to URL group could be done, but #301 basically supercedes it.

**Comment by dantheta** [comment]
Working on that last bit - the query for it is very expensive.  It's gluing together court orders without URLs, court orders with URLs and URLs without court orders in a full outer join.  The current version is blocked URLs which may or may not have a court order, which is a lot faster.  Will keep updating.

**Comment by JimKillock** [comment]
I can see that :) Could we flag an injunction as "No URLs associated" on the admin side and use that to list them in a separate, simpler query?

**Comment by dantheta** [comment]
I'd forgotten about UNION - thanks!  All sorted.  There's a court order with no sites on page 3 of the legal blocks list.
