### ISSUE TITLE
Report field abuse

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#254]
This:

https://www.blocked.org.uk/site/http://thestudentroom.co.uk

is an attempt I think at link farming. 

We should be able to delete user reviews that are abusive (the report itself may not be abusive).

**Comment by dantheta** [comment]
Yep, we can switch them to "not-published" very easily.

**Comment by JimKillock** [comment]
Is this covered by the flagging system? Or is there more to do? Checking in case it can be closed.

**Comment by dantheta** [comment]
Last couple of changes needed to be able to squash the comment without necessarily removing the whole report.

**Comment by alexhaydock** [comment]
Is this something the flagging system handles now?

I've seen quite a few of these in my testing but only just saw this ticket. I was really scratching my head trying to work out how the UX was confusing enough that people were submitting reports for apparently unrelated sites but @JimKillock's theory about link farming seems valid.

For what it's worth, that report still seems to be visible on the main site. I can track it down and flag it if that's what the flagging function does.

**Comment by dantheta** [comment]
That's what I'd expected.  It appears that flagging a report as abuse does not remove the comment from the frontend.  I'll need to check back on the commit history of this one.

**Comment by edjw** [comment]
@dantheta – What's the status of this? Can we remove comments when we flag a report as abuse?

**Comment by dantheta** [comment]
Yep, that's done now.  Comments are hidden on the frontend automatically.
