### ISSUE TITLE
Implement full tracking of complaints

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#256]
Create system to fully track all complaints, similar to Alaveti / WDTK:

* email address per user complaint
* store emails sent and replies
* make all complaints public by default

Depends on full user system with log in.

Worth investigating if integrating Alaveti would work in this context.

**Comment by dantheta** [comment]
This sounds very interesting.  Piping mail through postfix and into the database is pretty straightforward, and Python's MIME parser is quite nice.

**Comment by JimKillock** [comment]
@gwire suggested we start assigning unique emails to senders so that ISP replies can be routed via blocked.org.uk in any case, eg:

randomised-1938440@blocked.org.uk » forwards in our system to » actualemail@domain.com

I think this may be a neat solution as the ISPs avoid correspondence with the complainants, and sometimes they misdirect replies to our generic reply-to.

**Comment by dantheta** [comment]
That's what I was thinking too.  The system can slurp the ISP's reply into the database at the same time as it's forwarding to the complainant.

**Comment by JimKillock** [comment]
Give us a time estimate on this one Dan, so we can work out when to push it into development.

**Comment by dantheta** [comment]
I think 1 to 1.5 days.  Depending on how we want the mail routing to work, it might need a little bit of time from @gwire too.

**Comment by dantheta** [comment]
Emails are being successfully written to the database and relayed to the original reporter.
