### ISSUE TITLE
Name field error on adding Court order

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#262]
I got an error, that the court order could not be added as one of the fields was over 64 chars.

I am guessing it was "name" 

"Paramount Home Entertainment International Ltd & Ors v British Sky Broadcasting Ltd & Ors"

**Comment by dantheta** [comment]
Extended to 256

**Comment by JimKillock** [comment]
Still having problems editing, but now possibly with the save button? Changing "FAPL vs Sky" to "The Football Association Premier League Ltd v British Sky Broadcasting Ltd & Ors"
