### ISSUE TITLE
Name field error on save

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#267]
When changing "FAPL v Sky"' to:

"The Football Association Premier League Ltd v British Sky Broadcasting Ltd & Ors"

I get no save. is this to do with the quote marks perhaps?

**Comment by JimKillock** [comment]
Tried on  *Paramount & Ors v British Sky & Ors* – same result, a name change does not apply on save

**Comment by dantheta** [comment]
Fixed.  That was seriously odd.
