### ISSUE TITLE
Feedback received via email

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/blocked-org-uk#270]
The following notes were sent to me from Malcolm Boura:
- A have found a bit of a bug. I created a request to unblock and then spotted the "RE-CHECK SITE" button so I clicked it. The request to unblock was despatched, not what I expected. No harm done because the request was complete but that may not be true for other people.
- When I asked about www.bn.org.uk explicitly it only reported a BT-moderate block. I then made a generic naturism enquiry and looked at bn.org.uk which was listed as blocked by BT-strict. DNS lookup should enable the equivalence of the two to be determined.
- Second thoughts regarding the first. Perhaps it was not sent despite the page indicating that it had. A second unblock request resulted in an email asking me to verify my email address, unless of course it was a very slow response to the first.
- Also, it would be useful to get an email to provide a record of the unblock request.

**Comment by dantheta** [comment]
The BT moderate results are quite out of date - we don't currently have a line to test that filter setting.  When a result is more than two weeks old, the system notes the details in the unblock request and sends it once a successful check has been performed for the URL on the requests's ISP.  Unfortunately, with no test line the BT moderate entry will not be rechecked, and won't be sent.

I've hidden the BT-Moderate results from the frontend, so they shouldn't cause problems any more.

**Comment by JimKillock** [comment]
I think we can close this.
