### ISSUE TITLE
Clean lines for ISPs who fail to notify court orders with filters

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#274]
Some ISPs, eg Sky, O2, EE appear to be applying filtering before their network presents court order block pages, with the result that many / all sites blocked by court order do not appear to be blocked to our matches.

The obvious solution appears to be that we find clean line filters for:

* Sky
* EE
* O2

**Comment by JimKillock** [comment]
I'm going to suggest we reuse at least one of the TT lines as a clean line test facility. This can help compare the court order block results for instance as well as volume testing.

**Comment by JimKillock** [comment]
If we can get the clean line Sky probe working ASAP that would be very handy, as I will have a full set of errors in the copyright orders once that has run.

**Comment by JimKillock** [comment]
Some very strange inconsistencies which may be due to content filters. in many cases only one or two ISPs are blocking a site, due to administrative error. However, this may apply only to content filters so we need to test on clean lines.

For Virgin:

https://www.blocked.org.uk/site/http://torrentproject.com

https://www.blocked.org.uk/site/http://torrentproject.se 

BT has similar examples, for instance:

https://www.blocked.org.uk/site/http://torrentz.cd 

This, blocked by TT and Virgin only:

https://www.blocked.org.uk/site/http://losmovies.com

Thus we should redeploy the volunteer TT probe to test just copyright blocks, as well as get the Sky probe online asap. And locate BT / Virgin lines we can use.

**Comment by dantheta** [comment]
Sky clean is running as of last night.  It's taking part in the usual recirculation of tests.

**Comment by dantheta** [comment]
Reconfigured J's plusnet as a clean line.

**Comment by dantheta** [comment]
Reconfigured the volunteer TT probe as a clean line probe.

**Comment by JimKillock** [comment]
Two Virgin clean line probes on their way. Nearly there :)

**Comment by JimKillock** [comment]
Last one, BT, is agreed but not sent out.

**Comment by JimKillock** [comment]
BT clean line probe running
