### ISSUE TITLE
Re-checks not daily

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#277]
Some of the reported sites don't seem to be checked daily:

https://www.blocked.org.uk/site/http://www.milford-u3a.org.uk

When things get a bit further down the line we could put the checking / scheduling policies into the admin system.

**Comment by dantheta** [comment]
This was a misrecorded status; some of the CSV imported sites did not have the default robots.txt 'ok' status applied, so they were being excluded from recirculation.

**Comment by dantheta** [comment]
> When things get a bit further down the line we could put the checking / scheduling policies into the admin system.

I was thinking the same thing.  That would be pretty neat.
