### ISSUE TITLE
Test site in real time feature

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#278]
The front page 'test site' feature no longer works in real time, eg: 

https://www.blocked.org.uk/site/https://eng.forsaetisraduneyti.is

This should work in real time. I think there was some discussion elsewhere. Not sure if it is a bug or a change.

**Comment by dantheta** [comment]
I think it's hitting the rate-limiting feature.  Each URL can only be submitted through the frontend once a day (even if the request gets queued for longer than that).  If a URL has already been submitted, the frontend redirects the user to the results page.

I've checked it with a fresh URL just now, and I got the realtime results.

**Comment by JimKillock** [comment]
Hm, that's why I'd tried with Icelandic govt domains ;) 

https://www.blocked.org.uk/site/https://eng.umhverfisraduneyti.is 

similarly isn't giving me any results. As you can also see at:

https://www.blocked.org.uk/site/https://eng.forsaetisraduneyti.is

there are no tests run.

**Comment by dantheta** [comment]
https://eng.forsaetisraduneyti.is/robots.txt

Same for the other site.

We do need better feedback for cases where robots.txt doesn't allow the probe to test.

**Comment by dantheta** [comment]
I'll open a new issue for robots.txt display.
