### ISSUE TITLE
Filter status (probe page)

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#281]
Change filter status so that it indicates "filter is currently working as expected" or "filter is not working as expected", eg:

"OK: filter on"; "Error: filter off"

Where there is no filter, the column could indicate an error (filter detected) when a filter accidentally becomes enabled. In these cases it would report:

"Error: filter on" or "OK: unfiltered"

**Comment by edjw** [comment]
@JimKillock Is this issue about this page? https://www.blocked.org.uk/stats/probes

**Comment by JimKillock** [comment]
Yes, but the ticket is a year old. I am not sure if this is needed now.

**Comment by edjw** [comment]
Can this ticket be closed @dantheta?
