### ISSUE TITLE
“Probe down” owner reports

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#283]
Create email alerts sent to probe owners when their probe is down or unavailable, with instructions as to how to fix it, eg:

"Your probe [Name] in [Country] [Any other identifiers] is unavailable. Please restart the probe and ensure it is visible to you on your network.

"Ensure the red and green lights are flashing.

"The probe will re-register automatically. Your probe will be visible as available at: [URL]."

Alerts should repeat at least daily.

**Comment by JimKillock** [comment]
This is part of a wider issue we're beginning to see about probe management, eg, helping people know there are problems. We should probably support having multiple probe owners also, so the people managing the project in a country can follow up.

**Comment by JimKillock** [comment]
@dantheta I think we should tackle this next, as we're getting a lot of questions from people now, and it must be taking up your time more than necessary.

**Comment by dantheta** [comment]
I've set up a nagios instance on the API server which can watch all of the probes.  The email alerts are customizable, and the probe owners can even see the status on the web frontend (just their probe).  It's still in testing, so it isn't sending the email alerts for real just yet, but that should be doable in the next couple of days.

**Comment by dantheta** [comment]
The template can be improved further, but the basics are done.  More improvements to do to the template and to add in database checks (time since last result).
