### ISSUE TITLE
Legal blocks page times out

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#286]
You may know this already, but the legal blocks page is currently timing out:

https://www.blocked.org.uk/legal-blocks

**Comment by dantheta** [comment]
I've put a caching hack in for now.  The legal blocks data will update hourly, but the pages are fully browseable.

**Comment by dantheta** [comment]
The caching hack is holding, and adding in the court order info also helps the explain plan.  It's running fine now.
