### ISSUE TITLE
TT orders not being picked up

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#287]
See:

https://www.blocked.org.uk/site/http://extratorrent.com

On TT this directs to

http://www.siteblocked.org/extratorrent.html?accessurl=ZXh0cmF0b3JyZW50LmNvbQ==&urlclassname=ZXh0cmF0b3JyZW50&ipaddr=[redacted]

but seems to have been disregarded in our test.

**Comment by JimKillock** [comment]
Note: the TT URLs have indication of the source URL, and therefore the order applied, but it's not always accurate

**Comment by dantheta** [comment]
They used to always redirect to piratebay.html  regardless of the site that was blocked. Our rules need to be updated, which is easy to do. Since we record the final URL, we can easily identify the domains to rerun.

**Comment by dantheta** [comment]
Fixed - https://www.blocked.org.uk/site/http://extratorrent.com
