### ISSUE TITLE
Clicking 'See Another Blocked Site' causes full-page refresh

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#288]
On the homepage, when you click See Another Blocked Site in the 'Has this site been blocked in error?' section, there is a full page refresh. To the user, this means there is a delay and then the page jumps back to the top of the page.

This isn't such a big problem on wide screens as the section is close to the top of the page. On narrower screens though like phones, this is a big and confusing jump.

**Can the 'Has this site been blocked in error?' section dynamically refresh without a full-page refresh when the user clicks the 'See Another Blocked Site' button?** I'd be happy to look into the codebase and javascript to see how to get this done.

**Comment by dantheta** [comment]
Sure, that sounds cool1 The blocked in error region is defined in 

https://github.com/dantheta/blocked-frontend-py/blob/master/BlockedFrontend/templates/cms/index.html#L36

Javascript event handlers can be defined in that template by adding a block with:

```
{% block page_script %}
$(document).ready(function(){
  $('#buttonid').click(function(){
    // draw the rest of the owl
  });
});

{% endblock %}
```

The data for the _next url_  region comes from frontpage_lists in https://github.com/dantheta/blocked-frontend-py/blob/master/BlockedFrontend/cms.py.  This can be copied into a separate JSON call.

**Comment by dantheta** [comment]
This is fixed in openrightsgroup/cmp-issues/issues/251
