### ISSUE TITLE
Import blocks to block group list

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#293]
We have a nearly completed list of court order blocked domains (from the export) listed to block group.

Can we import this directly rather than C&P?

**Comment by JimKillock** [comment]
List is done and ready for import.

**Comment by dantheta** [comment]
Cool - if you mail it across, I'll get it imported and write a control panel feature to import similar files in the future.

**Comment by JimKillock** [comment]
As the file is large and quite complicated to assign each block of sites, you might want to just build the tool and use it for testing :) Up to you of course, whatever is convenient.

I'm not absolutely sure all the sites are actually in the court order domain lists we got. But they may be.

**Comment by JimKillock** [comment]
This should be the next on the todo list I reckon :)

**Comment by dantheta** [comment]
I've written an importer for the group:url mapping.  It currently imports urls into existing groups.  There are quite a lot of groups in the sheet that don't exist in the database yet; creating them is easy, but the system would need to know which judgment the URL group should belong to (or we would need UI to be able to move groups between judgments).  

I've added the unknown groups to a new sheet in the legal blocks Google Sheets doc.   If these groups are created under their corresponding court judgment, the importer will be able to add URLs to those groups when it is run again over the same input data.

Another option is to add the ID number for the judgment (visible as the last part of the URL in the edit screen) to each row, and I can import those groups against those judgments, then re-run the URL import.

**Comment by JimKillock** [comment]
Great work. How about listing the existing URL groups in alphabetical order on the page prior to import? Then we can at least see which are present prior to attempting import.

**Comment by JimKillock** [comment]
Thanks for all this Dan.

I've now imported as many of the URLs back into URL groups as I can. I may have muddled up some of the "watch series" URLs so will need to go back through them some point.

We will need to be able to:

* delete / unassign URLs from groups and court orders
* edit the names of the URL groups / delete URL groups
* using the existing court order blocks export tool, include the URL group and court order for checking and sorting the unassigned URLs

**Comment by JimKillock** [comment]
I should say that I would need the tools above to export, find the unassigned data, and then work on that, to finish the job :)

**Comment by dantheta** [comment]
Added the list of URL groups to the import form.

**Comment by dantheta** [comment]
To remove a URL from a group, select its checkbox and select the 'Uncategorized' group.

**Comment by JimKillock** [comment]
I've now done most of the sorting by hand so these changes aren't quite as high priority. There are a number of URLs that are listed as unclassified that need cleaning up - like sites duplicated due to capitalisation, or page URLs. I can help with this if you can give me an admin tool, eg a "duplicate" flag. This shouldn't be a public tool.

**Comment by dantheta** [comment]
I've just added a delete icon for the URLs, which will remove them from the court order.  If the entry doesn't exist on any other list, it's removed entirely from the legal requests part of the system.

**Comment by JimKillock** [comment]
Thanks Dan: presumably if deleted, it is still picked up as blocked by court order / uncategorised tho?

**Comment by dantheta** [comment]
Yes, that's right.  It's the attachment to the court order that's being deleted.

**Comment by dantheta** [comment]
Group delete is done too.

**Comment by JimKillock** [comment]
Thanks Dan :) I think we can close this. We still need a way to tidy up the clutter in the list, up to you how we do that however.

**Comment by dantheta** [comment]
OK, that sounds cool.
