### ISSUE TITLE
Sky court order URLs not being picked up

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#296]
Checking:

https://www.blocked.org.uk/site/http://mp3monkey.net

The Sky block page detected is the court order page:

http://blocked.nb.sky.com/?mp3monkey.net

so should be detected / listed as a court order block but currently is not.

On a quick look this seems to be the case at other domains. (Which is good news as it is easier to fix than requiring two probes, although we will have one for verification purposes.)

**Comment by JimKillock** [comment]
Seems that only sometimes are the Sky blocks clearly court orders:

http://block.nb.sky.com/?domain=btloft.com&categories=ANONYMIZERS&match_user_blacklist=false

is basically in the same format except it specifies a category, so is from the filter, not the court order list. Weird.

**Comment by dantheta** [comment]
It is a different subdomain though.  I've been testing the final URL results from the probes for the last few days, and it does seem safe to classify the blocked.nb.sky.com results as copyright blocks.  I'll run a retest of those through the clean lines, and we should then be able to see them better in the legal blocks pages.
