### ISSUE TITLE
Domain with and without slash on blocks

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#298]
http://www.couch-tuner.fr and http://www.couch-tuner.fr/ ought to be treated as the same URL, but are not. 

For this reason, court order 18 ( Twentieth Century Fox Film Corporation & ors vs BT & Ors, from 2017-11-20) wasn't listing on the court order page. 

I think this will in general cause some confusion. Is there any way we can get the system to understand the two URLs as being the same thing, or else to strip the final slash where it appears (as generally, they are missing)?

**Comment by JimKillock** [comment]
(Another thing we could do, is add an edit button so we can manually strip the / from the court order pages where it is added incorrectly)

**Comment by dantheta** [comment]
There's a URL normalization routine that is used in the API.  We can apply it in the frontend as well.  It removes the trailing slash if there's no path in the URL.

**Comment by dantheta** [comment]
It can be applies to the site URLs retrospectively as well.

**Comment by JimKillock** [comment]
Closing this as it's dealt with by the new admin tool at #299
