### ISSUE TITLE
Hide duplicate / page URLs

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#299]
Add a feature for admin users to hide duplicate blocked URLs such as:

http://www.watchseries.lt/Watch

*or* have a feature automatically to hide / exclude these from the list

**Comment by JimKillock** [comment]
Moving this up the queue as the next item.

**Comment by dantheta** [comment]
Page-level URLs are now hidden, and I've marked the case-variants as dupes.

**Comment by JimKillock** [comment]
Thanks Dan; two missed dupes: 

http://Yts.unblocked.lol

http://Watchseries.lt

Will you provide an admin tool so we can do this without bothering you each time? 

There are other admin-side things to do relating to court order URLs, such as flagging them as ISP mistakes, which we could do together at a later date.

**Comment by JimKillock** [comment]
(see #291 – I've added the flagging tool to that)

**Comment by dantheta** [comment]
URL admin tool is live.
