### ISSUE TITLE
Court order index

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#301]
Let's use the "legal blocks" page to list out each of the court decisions, with a link to the full block information per decision.

The information can include a total blocks per decision.

**Comment by JimKillock** [comment]
Also this one, moved up as a simple (hopefully) tidy up to the court order pages, so we can move on to the 451 and EU work.

**Comment by JimKillock** [comment]
Could we move this one up the queue?

**Comment by dantheta** [comment]
The first version is up now, linked from "Legal blocks" -> "Court order index".  Each order links through to a list of associated sites, which link to their results pages.

We can add more information about the court order to each of the court order (/legal-blocks/order/nnn).  The court order index page (/legal-blocks/orders) can have CMS/ModX text as well.

**Comment by JimKillock** [comment]
Thanks Dan. These looks good. These would be the next changes:

(1) https://www.blocked.org.uk/legal-blocks/orders should move to the /legal-blocks page

(2)  Base the "Sites listed" on the "groups" and call it "Services targeted". The sites on our lists for detection and testing are an internal matter only (source lists of possible blocks).

(3) Add in a statistic "Errors detected" based on errors noted on active blocks only

(4) Link the court order to the blocks summary as currently listed on the /legal-blocks page, but just for that court order

(5) We can retain the listing of all blocked sites if we like, at a separate URL.

**Comment by JimKillock** [comment]
Adding to this: if we use the approach above, we will also need a list of sites that we haven't grouped into a court order.

**Comment by dantheta** [comment]
The page switchover is done.  I'm refining the content on the order page (/legal-blocks/orders/XX).  Error stats are appearing next.

**Comment by JimKillock** [comment]
Thanks Dan, that's great. We will also need a link to the blocks not associated with a court I order I think. It might be a bodge but we could simply set up a "court order" that was for everything that *isn't* a identified under a court order. 

And also we will need the download feature back of course, I've been pointing ISPs to it so they can weed out errors.

**Comment by dantheta** [comment]
The export button and menu links are back.  Still working some knots out of the report page.
