### ISSUE TITLE
Tidy up court order exports

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#302]
Include in the court order export, for each record:

* Date of first detection
* URL group / groups (if assigned to more than one)
* Any flagging information from #291

This will help us maintain the lists, and flag errors to ISPs etc in the short term.

**Comment by dantheta** [comment]
The export file has been updated with the same layout as the web page version (on the UK site).  Sites which have been flagged as duplicate/invalid etc are omitted from this report.

**Comment by JimKillock** [comment]
Great work
