### ISSUE TITLE
Retain DNS expiry dates

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#303]
For court order blocked domains, retain DNS expiry dates

**Comment by dantheta** [comment]
This is being recorded for bare domain records (http://domain.tld).  It's capturing the registration expiry when a URL is submitted for testing, and will cache for 6 months or until expiry.  We can trigger an anomaly report if a URL comes up with a dnserror status from a clean line probe before the expiry date.
