### ISSUE TITLE
Double check on TT blocks

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#305]
I've asked for some manual checks on a TT line to check for court order blocks; and will report back if they are present but not being picked up

**Comment by JimKillock** [comment]
Manual check of:

manual check of:
http://couchtuner.bz 
http://couchtuner.fr
http://couchtuner.me
http://couchtuner.mx
http://couchtuner.video
http://mycouchtuner.ag
http://www.couch-tuner.fr
http://www.couchtuner.fr
http://www.couchtuner.onl
http://www.couchtuner.video
http://bmovies.is
http://fmovies.is
http://fmovies.se
http://fmovies.se
http://sockshare.net

showed all blocked except  sockshare.net

**Comment by JimKillock** [comment]
(checked up to http://onwatchseries.to off first page of results)

**Comment by dantheta** [comment]
Interesting - these are in-line responses similar to the plusnet ones.  No DNS hijacking, but injected page responses.  I've updated the rules and we can rescan those URLs.

The blocking page (which won't be visible outside of TT) contains a link to: http://www.talktalk.co.uk/blockedsites

**Comment by JimKillock** [comment]
Thanks Dan, I think it's now not picking up the blocks on TT Kidsafe for some reason, for instance: https://www.blocked.org.uk/site/http://watchseries.lt

**Comment by dantheta** [comment]
The kidsafe ones seem to be picked up OK now.  Adding a new rule shouldn't have affected the interpretation of existing rules, but TT always manage to surprise me.  I think we can close, but feel free to reopen if it reappears.
