### ISSUE TITLE
Server confuses blocked.org.uk and netblocked.eu

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#307]
After visiting both websites, the server seems to misunderstand which site's pages to serve so users get presented with pages from both domains and both domains.

**Comment by dantheta** [comment]
Is it the theme that's being mixed up ( the logo at the top), the results or the text (or some combination)?

**Comment by JimKillock** [comment]
It seems like the whole page content. I've sent a couple of screenshots via RocketChat

**Comment by alexhaydock** [comment]
It's happening even on first visit in a completely fresh Tor Browser

![screenshot](https://i.imgur.com/2P4RVX5.png)

**Comment by alexhaydock** [comment]
Potentially related, but https://www.blocked.org.uk/sites is serving a 404 on about every 1/3 visits for me, again even in a fresh blank browser.

**Comment by dantheta** [comment]
I've put in a fix which should sort it out. I'm no longer getting the 1/3 404 errors.

**Comment by dantheta** [comment]
It also means that netblocked and blocked can be updated separately even though they're from the same codebase.
