### ISSUE TITLE
New data

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#311]
I've sent over some data sources: 4 million general URLs, some specific IP addresses, 2-300 Pirate Bay clones (will include duplicates), some Catalonian websites possibly blocked in Spain.

Can we get tests going on these?

**Comment by JimKillock** [comment]
Ping on these as the next issue.

**Comment by dantheta** [comment]
The 4million list is resolving and importing; the others are done.  The catalan blocking may be more OONI's territory, but we can see if anything gets spotted.
