### ISSUE TITLE
EU and UK sites flipping

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#312]
I'm getting this still: it did reduce, but it is happening for me regularly at the moment.

On the admin side, this means I get a lot of errors on submit, while the requests are actually processed.

I want to send people to both sites to review and compare but I'm wary as they will get errors.

Will supply screenshots.

**Comment by dantheta** [comment]
I haven't been able to reproduce the problem this morning.  I've given everything a restart and made one more config change to try to eiliminate the problem.

**Comment by JimKillock** [comment]
Nor me this morning! I'll close it and let you know if it reappears.
