### ISSUE TITLE
GOV.UK domains

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#313]
I don't know if they've already been imported, but you can get a list of all registrations under gov.uk via https://government-domain.register.gov.uk

**Comment by edjw** [comment]
3,163 URLs
[gov-uk_domains.csv.zip](https://github.com/openrightsgroup/blocked-org-uk/files/2866022/gov-uk_domains.csv.zip)

**Comment by dantheta** [comment]
All loaded.
