### ISSUE TITLE
Share your stories

### ISSUE THREAD

**Issue by cmlb1879** [openrightsgroup/blocked-org-uk#315]
Add something like 'If your website has been blocked please get in touch here: blocked@openrightsgroup.org' on the 'Your Stories' page so that people who want to tell us their stories can

**Comment by edjw** [comment]
@dantheta – Let's do this.

Something like this at the top of the page…
"If your website has been affected by incorrect blocking, email us with your story at blocked@openrightsgroup.org"

**Comment by dantheta** [comment]
Sure - are you thinking of a banner/callout  at the top of the frontpage (or all pages?)

**Comment by edjw** [comment]
Just on the "Your Stories" page
