### ISSUE TITLE
Normalise base URLs (e.g. to end in trailing slash)

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#321]
The backend editor (eg for grouping court orders) seems to include doubled up entries for both `http://www.example.com` and `http://www.example.com/` suggesting they are two separate database entries, but the frontend seems to show the same record for both.

**Comment by JimKillock** [comment]
AIUI the database has just http://www.example.com – so the entries in the control are just (my) user error.

**Comment by dantheta** [comment]
This has been fixed in #329 for new records.  The non-trailing slash version was preferred on the main site (to improve readability), so the same convention has been kept here.
