### ISSUE TITLE
Switch off autocomplete for mail website check form

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#325]
Can we set `<input autocomplete="off" ... />` for the website check box.  I've tried typing in urls, only to have the browser helpfully insert spaces or "fix" the spelling.

(This is the [W3C standard](https://www.w3.org/wiki/HTML/Elements/input/text) , I believe the other `autocorrect` and `autocapitalize` settings are not.)

**Comment by dantheta** [comment]
Might also help sort the Http:// URLs we get.

On 13 February 2018 13:34:07 GMT, gwire <notifications@github.com> wrote:
>Can we set `<input autocomplete="off" ... />` for the website check
>box.  I've tried typing in urls, only to have the browser helpfully
>insert spaces or "fix" the spelling.
>
>(This is the [W3C
>standard](https://www.w3.org/wiki/HTML/Elements/input/text) , I believe
>the other `autocorrect` and `autocapitalize` settings are not.)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantheta** [comment]
Done.
