### ISSUE TITLE
siteblocked.org is TalkTalk's blocked page

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#327]
http://www.siteblocked.org is [listed](https://www.blocked.org.uk/site/http://www.siteblocked.org) as being blocked by a High Court Order.

But, this seems to be used by TalkTalk to convey information about court blocks. The domain is currently registered to them and the page links to talktalk's support page.

(Of course, it's strange that O2, EE, Three, and Sky are blocking it via adult filters...)

**Comment by dantheta** [comment]
Yep, this is an odd edge-case.  The probe recognizes the correct patterns in the page, but there isn't a way to mark the result in the database just for one ISP.  More complicated rule handling would be required in the probe to correctly categorize this result.

**Comment by JimKillock** [comment]
I don't quite understand this, surely we have the same problem with the other generic court order websites, such as the one BT uses? 

Here's two possible bodgy solutions, in order of preference:

Could we suppress the TT result in the DB?

Could we could hide the site from public record?

**Comment by dantheta** [comment]
That makes sense - I was trying to thing of a way to prevent them being identified as blocks, but this is simpler.  I've added a new URL status (restricted-by-admin) which will allow us to override the submission and recirclation of URLs for administrative reasons.  I've also removed the blocked results for this domain (though the historical measurements are still stored).
