### ISSUE TITLE
Admin page for court blocked sites where order is not known

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#328]
One of the things I've been doing is checking the final entries in [legal blocks](https://www.blocked.org.uk/legal-blocks) to check for new entries that need to manually associated with known court orders, which involves navigating to the page (since the url changes) and eyeballing the list for new entries.

It would be good to have an admin page that lists the unassociated court blocks in the order that they were identified as being court blocks, in order to speed up the association process.

**Comment by dantheta** [comment]
There's a new menu entry in the control panel for the unmatched copyright blocks report.

I'm also thinking of adding a URL format categorizer that will allow us to filter URLs depending on whether they are domain, subdomain or full page URLs, and also to normalize the scheme that is in use (mentioned in another issue, cross-matching http and https URLs).

**Comment by dantheta** [comment]
This looks pretty complete.  Feel free to re-open if changes are needed!
