### ISSUE TITLE
Court ordered block domains should not be case-sensitive

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#329]
Both `http://primewire.unblocked.bz` and `http://Primewire.unblocked.bz` are listed as separate entries in the court-ordered blocklist.

* https://www.blocked.org.uk/site/http://Primewire.unblocked.bz
* https://www.blocked.org.uk/site/http://primewire.unblocked.bz

**Comment by dantheta** [comment]
New domains that are added through the court order system will be normalized.  The scheme and netloc parts of the URL will be converted to lower case.  The path component (if present) will retain its original case.  The http scheme will be added if none is present.

URLs that are already there will be converted using database edits, or deleted if a normalized-case version exists.

**Comment by dantheta** [comment]
I've cleaned up some of the lower vs title case duplicates and https vs http duplicates.
