### ISSUE TITLE
Categorize domains by type

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#330]
Add category column for DOMAIN, SUBDOMAIN, PAGE, and a function to get the parent URL.  

This can help cut down duplication of court orders and block reports.

**Comment by JimKillock** [comment]
This looks like a good idea Dan

**Comment by dantheta** [comment]
This is backfilling data now.  We can use this to reduce duplication in the injunction and parental filtering reporting.
