### ISSUE TITLE
Results page for incorrect legal blocks

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#331]
create page at /legal-blocks/errors

Present statistics:
* Total sites blocked by Injunction
* Total sites incorrectly blocked by Injunction
* Error rate as %age
** Error rate as %age per ISP

Error categories table
* Total Errors
* Total Error per ISP
* Total error per category

Error sort page
* List of flagged URLs (linking to report page)
* Sort by error type, ISP, injunction

**Comment by dantheta** [comment]
The first version is live at https://www.blocked.org.uk/legal-blocks/errors.  At the moment the entries are drawn from blocks across all ISPs - it doesn't drill down to ISP level yet.

**Comment by JimKillock** [comment]
Thanks Dan: what is causing the disrepancy between the legal blocks page figure ("1190 sites detected") and the error page figure: ("1,689 sites blocked by injunction")?

I'm assuming the lower figure is the more useful one?

**Comment by dantheta** [comment]
The new report page was using URLs across all territories, rather than restricting to GB (as the legal-blocks) page does.  They are now both reporting based on the geographical set of URLs.

**Comment by JimKillock** [comment]
Ah right, great :)

We will work on the data next week and will let you know if anything else springs up :)

**Comment by dantheta** [comment]
Cool.  Do you want it to drill down to ISP level at this stage?  If so, we'll need to decide whether it should focus on the ISPs that the court orders target or the ISPs that the block has actually been detected on (and do the cross-referencing to find out if&where they are different).

**Comment by JimKillock** [comment]
Hm … 

(1) ISPs should not be blocking anything that is not subject to a court order. 
(2) We don't always know why a site is blocked and why it was identified as subject to a court order, nor which court order
(3) With many URLs / sites, we assume they are clones and identify them with likely court orders
(4) We identify per URL / site that they are no longer infringing and flag them
(5) Some ISPs are less efficient than others at maintaining their block lists 

I think therefore we should focus on the known elements: the ISP declares a block to be due a court order, and we know the site is no longer infringing.

So the simple thing is to say: this number of incorrect blocks, of these types, exist per ISP.

**Comment by dantheta** [comment]
Errors by ISP has been added.  The page layout can still be tweaked to balance things out a bit.  I might put the large stats block above "Errors by type", so that there are two columns at the top.

**Comment by JimKillock** [comment]
Great, thanks Dan. Two questions / comments:

(1) List the "unfiltered" networks subject to court order blocks, so BT / Virgin / PlusNet / Sky / TT first; plus any of the mobile networks we know are (still) doing this (it has changed over time).

For results from filtered networks, we would need to explain why the numbers are lower (ie, that many URLs are blocked for filtering reasons and the court orders are not mentioned to users).

(2) Why though does BT (unfiltered) show just 163	injunction blocks? This must be wrong, as the results pages show that network as blocked most of the time as you would expect

**Comment by dantheta** [comment]
The ISPs list has been updated so that it only shows fixed unfiltered and mobile lines.

For the BT unfiltered count, BT have added a new page response (this one injects a 200 response with content that links to ukispcourtorders instead of redirecting).  The rules have been updated and I'm re-running all known copyright blocks against BT Unfiltered.

**Comment by JimKillock** [comment]
One query:

(1) We have identified more incorrect blocks than are listed: we'd like to double check why this is; I am assuming it is maybe because the incorrect blocks identified on the admin side are not currently listed as blocked by any ISP

and a couple of things to change:

(2) The list needs a scroll to extra pages

(3) The arrows needs to list in ascending / descending order

**Comment by dantheta** [comment]
(1) Yep, that's right for the majority of cases.  There are few cases where a block exists but it isn't categorized as a copyright block or the ISP where a block exists is outside the GB territory.

To make flagging a bit easier, I've added the current block status to the flag page.

**Comment by JimKillock** [comment]
I'm sure this is all done so closing
