### ISSUE TITLE
Remove injunction flag information

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#333]
Create ability to remove the information from a flag (record created in error), or create a new flag (new status).

Normally a flag should persist as a prior observation, rather than be removed entirely

**Comment by JimKillock** [comment]
Mistakes, for ref:

http://couchtuner.mx
http://couchtuner.video
http://itswatchseries.to 

need unflagging / deleting the flag entry

**Comment by JimKillock** [comment]
Could we also add a "checked" flag with date, so that we can record sites as observed " block appears correct"?

I think this would make the data more robust.

**Comment by dantheta** [comment]
Added.  There is now an "unflag" button on the flag screen.  Changes to the flag options are also written to a history table, which is shown below the editor form.

**Comment by JimKillock** [comment]
Thanks Dan, can we have the ability to delete a particular history entry (because the observation was incorrect) or mark the observation as incorrect?

**Comment by JimKillock** [comment]
Unfortunately there are quite a few entries I will need to delete, so this will be quite important to get the data up to scratch.

**Comment by dantheta** [comment]
No  problem, I'll have that fixed tonight.

On 6 April 2018 15:17:13 BST, JimKillock <notifications@github.com> wrote:
>Unfortunately there are quite a few entries I will need to delete, so
>this will be quite important to get the data up to scratch.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JimKillock** [comment]
Thanks, if you can add an alert symbol where there is any prior flagging that would also be handy (on the index page showing all the sites per injunction). That would let me scan down the list to see what needs to be double checked, if an old in-error flag has been recorded and removed. Else, I will have to check each entry.

**Comment by dantheta** [comment]
Deleting a historical flag is now possible (there is a trashcan link in the history section).

The number of flags for a URL is now shown on the URL listing screen as well.

**Comment by JimKillock** [comment]
Thanks Dan. One final thing we could do: 

* allow a user to add that a site has been checked (without finding a concern), on a particular date, from the "flag" screen

This would help us to do re-checking in the future.

**Comment by dantheta** [comment]
Already added :) There's a "block appears correct" option in the list of flag options.

**Comment by JimKillock** [comment]
That's great Dan: although as it is not a error, it needs to be omitted from the list and calculations at 

https://www.blocked.org.uk/legal-blocks/errors

(eg, not appear in "errors by type" and in the total of "sites incorrectly blocked")

Also, they should not appear in the list of incorrect blocks and not in the per-ISP totals.

I was thinking this might be a bit complicated … would it be easier to do as a different flag? Up to you of course.

**Comment by JimKillock** [comment]
Alternatively: you could leave it as is, *but*:

* ensure the total incorrect blocks discounts “Block appears correct”
* ensure the percentage calculator discounts “Block appears correct”
* Change "Errors by type" to "error status by type"

That seems simpler and you may have already done the first two?

**Comment by dantheta** [comment]
Ah yes.  Those are done now.
