### ISSUE TITLE
Add "reverse proxy failure" as a flag state

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#339]
Domains where the server is gone, but still point at a valid reverse proxy (such as Cloudflare giving a 52x status), can only be determined as "down" based on multiple observations over time.  Please add a specific category for this type.

**Comment by JimKillock** [comment]
Is this in relation to injunction errors, or flagging of filtered URLs?

**Comment by gwire** [comment]
For flagging the section 97a blocks - you can flag the site as down, but it might actually be a temporary state.

**Comment by JimKillock** [comment]
OK: question, how many of these do we have in the data set that may be mis-attributed?

**Comment by JimKillock** [comment]
@gwire Did you spot many reverse proxy errors? I'm asking as we will need to re-flag tbe results and this will be some work for someone
