### ISSUE TITLE
Fundraising on the page

### ISSUE THREAD

**Issue by MarthaDark** [openrightsgroup/blocked-org-uk#340]
Can we cage the donation banner across the top so that it is to the right go the page. Can it instead say that 

You can join the Open Rights Group or donate to support the project.

Support Blocked!
With your help, we can correct mistakes caused by overblocking and improve transparency about filtering in the UK. We need to raise £5,000 to continue this work so please support the project today!

**Comment by JimKillock** [comment]
Can we also have a donate button (based on PP button) as here:

https://www.privacynotprism.org.uk 

PP button code for Blocked:


< form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
< input type="hidden" name="cmd" value="_s-xclick">
< input type="hidden" name="hosted_button_id" value="NPU6HTUCX53QQ">
< input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
< img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
< /form>


PP non-tracking form from Privacy not Prism:

		<div >
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="EQVW9FQ7SMH8A">
				<input type="submit" class="text_donate" value="Donate">
				
			</form>
		</div>

(we'd want to avoid embedding it for style and tracking reasons)

**Comment by dantheta** [comment]
On 23/04/18 16:46, MarthaDark wrote:
> Can we cage the donation banner across the top so that it is to the right go the page. Can it instead say that 
> 
> You can join the Open Rights Group or donate to support the project.
> 
> Support Blocked!
> With your help, we can correct mistakes caused by overblocking and improve transparency about filtering in the UK. We need to raise £5,000 to continue this work so please support the project today!
> 

The text changes are fine, and the non-tracking button will work fine.

I'm  not quite sure what you mean with caging the layout? (apologies if
this was a mobile typo - I'm terrible for those)

If you would like to send a rough sketch, that'd be really useful!

 It's also worth keeping in mind that although we've got wide borders on
the left & right on widescreen monitors, these go away on smaller
desktops and on mobile.  We can fall back on the existing banner
position for these displays though.

**Comment by JimKillock** [comment]
caging: changing?

**Comment by JimKillock** [comment]
Thanks Dan: changes — 

(0) Change "support blocked" to "We need £5,000" 

(1) Delete the line "You can join the Open Rights Group or donate to support the project."

(2) Change "With your help, we can correct mistakes caused by overblocking and improve transparency about filtering in the UK. We need to raise £5,000 to continue this work so please support the project today!" to

"We need £5,000 to obtain all the court documents and make blocking and its mistakes fully transparent. Please donate today."

(2) Make the donate button about 200% bigger

**Comment by dantheta** [comment]
Updated!
