### ISSUE TITLE
Changes to sort and export

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#341]
We have had some bad data added to the reports, unfortunately, which needs further checking.

In order to make these checks, we need to be able to sort the dataset to look for specific kind of reports, rather than examine each one via the admin pages. 

Can we: 

1 add the error status to the export tool on the 'legal block' page

2 change the behaviour of the scroll-through on the 'errors' page, so that it obeys the sorting requested, eg if sorted by error type, page 2, is page 2 of results sorted by error

**Comment by dantheta** [comment]
On 25 April 2018 12:05:46 BST, JimKillock <notifications@github.com> wrote:
>We have had some bad data added to the reports, unfortunately, which
>needs further checking.
>
>In order to make these checks, we need to be able to sort the dataset
>to look for specific kind of reports, rather than examine each one via
>the admin pages. 
>
>Can we: 
>
>1 add the error status to the export tool on the 'legal block' page
>

I think this exists already - I can remember writing it, at least :)


>2 change the behaviour of the scroll-through on the 'errors' page, so
>that it obeys the sorting requested, eg if sorted by error type, page
>2, is page 2 of results sorted by error

I can fix this quite quickly.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JimKillock** [comment]
Thanks, yes, there is a column "reason" with error reports. There is a bit of info missing that would be helpful, "domain may be abusive", if that or another column could record the options (clickfraud/redirects ; malware). 

It is the redirects that are misclassified – one user recorded that any redirect was recorded as abusive, where these are better marked as 'block appears correct'.

**Comment by dantheta** [comment]
On 25 April 2018 12:05:46 BST, JimKillock <notifications@github.com> wrote:
>We have had some bad data added to the reports, unfortunately, which
>needs further checking.
>
>In order to make these checks, we need to be able to sort the dataset
>to look for specific kind of reports, rather than examine each one via
>the admin pages. 
>
>Can we: 
>
>1 add the error status to the export tool on the 'legal block' page
>
>2 change the behaviour of the scroll-through on the 'errors' page, so
>that it obeys the sorting requested, eg if sorted by error type, page
>2, is page 2 of results sorted by error


I've added a quick fix for this.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantheta** [comment]
The export function has been updated.
