### ISSUE TITLE
Add "No court order identifiable" to error types

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#344]
On the error status reports for copyright blocks, add a "No court order identifiable" option.

**Comment by dantheta** [comment]
That's been added.

On 24 May 2018 12:21:03 BST, JimKillock <notifications@github.com> wrote:
>On the error status reports for copyright blocks, add a "No court order
>identifiable" option.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JimKillock** [comment]
Thanks Dan: can you add this to the front end also?

**Comment by dantheta** [comment]
It should appear on the public part of the site whenever that flag is used for a court order.

**Comment by JimKillock** [comment]
I think this is done and can be closed
