### ISSUE TITLE
Import data from Citizen Lab censorship tests

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#353]
Citizen Lab publishes lists of blocked sites in various countries (not limited to local political censorship) - can these be imported (chopped to the domain level) into the test list for blocked.org.uk

https://github.com/citizenlab/test-lists/tree/master/lists

**Comment by JimKillock** [comment]
I think this dataset and the Common Crawl dataset should be imported so we can get cracking with these tests.

**Comment by dantheta** [comment]
These are imported and ready for testing.
