### ISSUE TITLE
Front page stat "27,565,320 sites tested"

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#355]

**Comment by JimKillock** [comment]
Hi Dan

I guess this means 'fully tested' or something similar? Could we have a figure that gives a better indication of the actual no of sites that have been partly tested?

**Comment by dantheta** [comment]
This number is accurate, and represents partial (i.e not all networks) results - we're currently adding half a million a week (which, with an average number of networks is 6 million results per week).  I've identified a bottleneck during the the URL queueing that will let us open the throttle wider.

**Comment by dantheta** [comment]
The bulk testing from the scheduler is currently suspended (disk space), but they're still trickling through from the original requeue system.  The status on the test scheduler control panel will catch up when it's running again.
