### ISSUE TITLE
Add extended description on site-specific block pages

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#356]
When an entry from the curated list, the extended description/title information is displayed.
e.g. "CUJO - Cambridge University Jazz Orchestra"

However this information is not shown anywhere on the "/site/" link
https://www.blocked.org.uk/site/http://www.cujo.org.uk

It should probably be displayed, when recorded, in the `<div>` under the `<h1>` for the domain.

**Comment by dantheta** [comment]
That's live now.
