### ISSUE TITLE
Surface IP address of site being checked

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#357]
For each ISP, please display (although not predominantly) the IP address that was being checked.

This has some relevance where sites are using multiple IP addresses and some may exhibit different behaviours in different circumstances. (e.g. are we testing IPv6, is it a dynamic CDN endpoint, etc)

**Comment by dantheta** [comment]
The result IP is now shown in the results table for admin users when logged in.

**Comment by gwire** [comment]
This would be more useful as the initial IP address resolved, rather than the IP address of the site that served a page (which in the case of blocks it usually some general ISP address.)

We are seeing sites that resolve to multiple IP addresses for which one IP address is blocked, so it would be useful to see which one.

**Comment by edjw** [comment]
Can this be closed?

**Comment by edjw** [comment]
@dantheta – Can this be closed?

**Comment by dantheta** [comment]
It's currently returning the IP of the final server after following redirects - I think gwire wanted the IP address for the domain that was requested.  It's only a small change, but I'm afraid I hadn't got to it yet.

**Comment by dantheta** [comment]
This will go live when the new version of the probe is rolled out.
