### ISSUE TITLE
Email body text to ISPs should clarify enquiry is not from ISP customer

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#369]
Occasionally ISP customer response will reply to blocking enquiries as though they are coming from an ISP customer, and request further details about their account.

We don't currently prompt to allow the user to state if they're the ISP's customer or not, so I think the body text should communicate that they may not be.

**Comment by edjw** [comment]
@gwire – Is this what you were thinking of?

@dantheta – Can we add this text to the bottom of the emails?

>(This report was made through the[ Blocked.org.uk](https://www.blocked.org.uk) service. The user making the report may not be a customer of your ISP.)

**Comment by dantheta** [comment]
I've updated the template here: let me know if it looks OK, or feel free to try out different wording.

**Comment by edjw** [comment]
Yep that looks great. Thanks Dan

**Comment by dantheta** [comment]
Cool!  That's live now.
