### ISSUE TITLE
Add a re-test this URL button to site blocking report page

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#370]
It would be useful to be able to quickly request a re-test of a URL from the status page about it.

So on this page for example [https://www.blocked.org.uk/site/http://www.diagnosteq.co.uk](https://www.blocked.org.uk/site/http://www.diagnosteq.co.uk)…

Can we add a button to re-test www.diagnosteq.co.uk ?

**Comment by dantheta** [comment]
We did used to have this, but removed it to streamline the reporting process and cut down visual clutter for end users.  When a site is reported for unblocking, the system automatically rechecks it then.

There is a force check URL function on the frontpage of the admin panel.  

I could add a re-test button on the site status page that's only visible to logged in admins, if that sounds good?

**Comment by edjw** [comment]
> We did used to have this, but removed it to streamline the reporting process and cut down visual clutter for end users.

Visual clutter is obviously an issue. At some stage we should look again at what people on these pages want to achieve and then prioritise elements on the page based on what people want to do. It might be that non-admin users would really like a re-test button but not be that bothered by a ’Try another site’ button that takes them to a random site blocking report, for example.

> I could add a re-test button on the site status page that's only visible to logged in admins, if that sounds good?

Yep I think that’d be fine for now. Thanks Dan

**Comment by dantheta** [comment]
Re-check site button is present.  Forgot to close this one a while back!
