### ISSUE TITLE
Investigate O2 non-replies

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#373]
It seems that O2 have not replied to any requests for over a year.

@edjw can you check the O2 official address for requests? I think we may want to revert to their media requests address as that they did respond to.

@dantheta can you let us know what the O2 and Vodafone address we are using is?

**Comment by alexhaydock** [comment]
This is largely why I requested the ability to folder via ISP and that's been quite useful, though maybe openrightsgroup/cmp-issues#188 would be useful here for tracking issues like this as we go forward?

Some other observations:
- Vodafone never seem to send follow-up replies after the initial automated one that says _"we'll be in touch shortly"_.
- TalkTalk are listed as having never replied to anything ever (is something broken?).

**Comment by edjw** [comment]
[This page on Blocked](https://www.blocked.org.uk/check) suggests we're using shieldav@o2.com as the email address to contact O2. That's also the email address [the BBFC gives on their site](https://www.bbfc.co.uk/about-bbfc/links) today.

O2 seem to only offer calling a number – 202 – to report a url. https://www.o2.co.uk/help/safety-and-security/age-restricted-content-and-age-verification. I've had a look in archive.org and can't see a time when that page mentioned shieldav@o2.com. Archive.org's earliest capture of that page is March 2016. I've done a Google Site Search for shieldav@o2.com on O2's site and there were no hits

**Comment by dantheta** [comment]
The O2 & Vodafone error submission addresses used by the system are:

 O2          | shieldav@o2.com
Vodafone    | Contentclassification@vodafone.com

**Comment by alexhaydock** [comment]
Do we know what the deal is with TalkTalk and the system showing that they're not replying to any reports?

**Comment by edjw** [comment]
O2 has confirmed by email that "ShieldAV@o2.com or ShieldAV@telefonica.com are the correct addresses for enquiries or review of URLs."

**Comment by JimKillock** [comment]
TT emails seem to go to homesafe.classification@talktalkplc.com on the system. There are no replies however. I will follow up with them directly.

**Comment by dantheta** [comment]
O2 and TalkTalk are answering now.
