### ISSUE TITLE
Display counts on list pages for "Unblocks Requested", and "Unblocked"

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/blocked-org-uk#376]
On list pages on the main Blocked site, it would be useful if totals were displayed next to the `xx entries` header for:
* Number of list entries for which an unblock has been requested.
* Number of list entries which have been unblocked.

Ideally this would be per-site figures and not per-request figures.

**Comment by dantheta** [comment]
Deployed.

**Comment by edjw** [comment]
@alexhaydock – Does this let you do what you wanted to? The stats are on this page (https://www.blocked.org.uk/lists) but not the individual list pages.

**Comment by JimKillock** [comment]
There's a slight comparability problem: the number of unblocked URLs needs to be compared with the total number of blocks, as well as the number of domains affected.

**Comment by JimKillock** [comment]
Reopening this: the stat columns need to show:

* Entry count
* Number of entries reported
* Number of ISP blocks found
* Number of ISP blocks lifted

Otherwise we can't compare like with like.

@edjw we think this is needed to help us finish the stats

**Comment by edjw** [comment]
@dantheta – Can you take a look at this?

**Comment by dantheta** [comment]
I've got a version of this ready to test, but it's awfully slow because we've added in the status from the probe result tests (previously it was only using the ISP reports).  I can add caching, but it means the results won't be up to the second.

I'm assuming that the `number of ISP blocks lifted` should be driven only by the ISP reports verdict, and not the detected probe status as well.  I can change this pretty quickly if needed.

**Comment by dantheta** [comment]
New version is deployed.

**Comment by JimKillock** [comment]
Thanks Dan, some delay or caching is fine: we're after a best effort comparability here, as the data is going into a static report.

**Comment by alexhaydock** [comment]
I think there might be some doubling of the statistics here. Looks like the lists seem to be detecting twice as many blocks per-list as there are sites in some of the lists.

"Weddings" has roughly 4500 entries but apparently 8600 blocked sites in it. Are the figures getting multiplied by 2 somewhere?

**Comment by JimKillock** [comment]
@alexhaydock The 8600 is a figure for all blocks over all ISPs as I understand it. That is why it is higher.

However there still seem to be some bugs:

https://www.blocked.org.uk/lists shows that cement has just two reports made and one unblock; 

https://www.blocked.org.uk/list/Cement shows several reports and unblocks on the first page.

Also: I made an error in the columns needed, as we also need a figure for "Entry count still blocked".

**Comment by dantheta** [comment]
The reported badge on the list page is currently shown for items where an ISP report exists in any state, but the reports total on the lists summary page is for ISP reports that were actually sent.

All of the ISP reports in the cement category apart from two are in the cancelled state.

For the `entry count still blocked` column, should that be based on ISP reports submitted (but not unblocked) or the detection system's view of which sites are still blocked?

**Comment by JimKillock** [comment]
OK, in that case we should make the flags consistent with the summary. 

I think it makes more sense to show reports that are sent, rather than ones that were raised but not sent. That said I am surprised it is only two, as I have sent at least a dozen relating to concrete, though perhaps that was not from this list.

For "entry count still blocked" this should be the total of sites actually blocked according to the detection system. 

(The aim of these stats is to illustrate the scale of potential errors yet to be reported, beyond what has been reported to ISPs and analysed by us.)

**Comment by dantheta** [comment]
OK - I'll need to do some testing with that one.  That flag is also used to decide whether to make the "report site" button available, and we don't currently support reporting a site which has already been reported but not user-verified.  I don't think the list presentation has any impact on the report stats, so is it OK to write it up as an issue for the backlog?

Working on the entries still blocked now.

**Comment by JimKillock** [comment]
Yes, thanks Dan, we can resolve the flag issue later, it doesn't need fixing today. Let me know if we can help work out the issue with counts - I could for instance look through the reports we've classified as "Building and construction" and compare them with the concrete list.

**Comment by JimKillock** [comment]
Thanks Dan: looking at "ISP blocks lifted" - I am guessing this is calculated against our requests? I think it would be better for it to be the total number of ISP blocks that we have detected have gone. That would hopefully make some sense of the other columns for someone reading the table.

**Comment by dantheta** [comment]
OK, I'll get that switched over.

**Comment by JimKillock** [comment]
Actually, could you replace it with (or add) a column for "Current ISP blocks"? This would be directly comparable with the total "ISP blocks found" which presumably is the total of blocks originally present.

**Comment by dantheta** [comment]
They're both done.  I added the extra column, so the totals can be viewed for list items and network blocks.

**Comment by JimKillock** [comment]
That’s great Dan, I think it’s a lot clearer now.

**Comment by JimKillock** [comment]
Further thought: would it be possible to add a total row at the bottom?

**Comment by JimKillock** [comment]
I'd still like to total row, especially if it were dynamic, eg something we could combine with the ISP filtering in #241

**Comment by dantheta** [comment]
Totals row added to the lists view.
