### ISSUE TITLE
Possible bug showing "Unblocked" in lists

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/blocked-org-uk#378]
In some lists, the system is showing the "Unblocked" badge on every URL in the list, even ones which I have forced a re-check for and determined are still blocked today.

It doesn't seem to happen on every list, but this one is an example:

https://www.blocked.org.uk/list/Cement 

I'm not sure if there's anything notable about this list. It's quite an old list, but I did use the list merge tool in the backend on this quite recently, to roll 2 or 3 lists into this one.

**Comment by edjw** [comment]
@dantheta - Would you mind taking a look at this and seeing if there's an issue?

**Comment by dantheta** [comment]
Yep, there is a bug here.  The daily update to the savedlist item is only paying attention to results from the last two weeks (for some reason - I'm sure it seemed correct at the time).  

The script has been updated, and will update the list items over the next few hours.

**Comment by edjw** [comment]
I just reopened this issue @dantheta as the bug seems to still be affecting the results

**Comment by dantheta** [comment]
See openrightsgroup/cmp-issues#240
