### ISSUE TITLE
Average reply interval (all ISPs)

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/blocked-org-uk#381]
We should calculate an average reply interval across all ISPs for headline purposes.

For the purposes of not including any recent reports which ISPs may still be in the process of replying to, I propose that this just includes data from 2018.

It should calculate an average response time for all ISPs using the same formula we're using to currently calculate the response time per-ISP, but should exclude non-responsive ISPs from skewing the calculation (TalkTalk, Plusnet, O2).

Ideally this would be calculated from the actual report figures for accuracy, rather than just by averaging the figures we already have in the respective "2018" rows for each ISP.

**Edit:** I just realised I put this in the wrong issue category, sorry.

**Comment by JimKillock** [comment]
This is done.
