### ISSUE TITLE
Update Recently Reported sites URL response time data

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#386]
Update the ISP section at the top of the Recently reported sites page with the new way of measuring response time.

Make sure the “Reports Sent” and “Sites Unblocked” columns are accurate and correct them if they are not

**Comment by dantheta** [comment]
The table at the top of recent reports has been updated to draw upon the same data as

https://www.blocked.org.uk/stats#notonlyadult

Note that the recent reports table uses data from 2018 onwards (when we started recording replies) and is not broken down by year.  I've added the responses count (number of reports that have received a response), but this field is used for the average calculation.

The old table had the average unblock time, but the new table uses average response time - the end result could have been an unblock or a rejection.

**Comment by JimKillock** [comment]
I'm not sure this works, if we are talking about the table here:

https://www.blocked.org.uk/reported-sites 

For an end user, it makes it look like many ISPs are doing nothing with our reports, which isn't really true. Some aren't sending us emails but are unblocking sites, and so on. This is why our tables in the stats pages are more detailed, and try to explain in more detail what is taking place.

I would simply remove the table from this page, as the information in the stats pages makes more sense.

**Comment by JimKillock** [comment]
As it stands I think it needs to be removed while the launch takes place. The data is sufficiently prominent and confusing enough to cause questions and uncertainty from the media and / or inaccurate reporting. We can come back to it if we want but for now I'd like it removed.

**Comment by dantheta** [comment]
Yep, that works.
