### ISSUE TITLE
Frontpage reworking

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#387]
- [x] Top black banner: “A transparency campaign” rather than “Transparency campaign”
- [x] Remove Donate banner (template change across the site
- [x] Navigation menu
- [x] Main title “Why are websites being blocked in the UK?“ -> Rewrite: “Is your website being blocked?”
- [x] The main blurb: reduce the width so there’s a bit more whitespace to its right
- [x] Move the ‘Check a website’ form
- [x] The top-level stats section: make it span horizontally across a row
- [x] Move the ‘Has this site been blocked in error?’ box
- [x] Supported by Section
- [x] Share your story’ section at the bottom of the page
- [x] ‘Spread the word’ section
- [x] Add a footer (everywhere on the site) with STAY IN TOUCH, SUPPORT, CREDITS PROBES STATUS, GET INVOLVED, DONATE, CONTACT, PRIVACY POLICY

**Comment by JimKillock** [comment]
Note that the sketch didn't show two changes:

* Move the ‘Has this site been blocked in error?’ box to the *left*
* Move the general blurb to the *right*; make this visually related to the “Is your website being blocked?” form so that it can explain the form.

**Comment by dantheta** [comment]
Layout and text changes are done (hopefully I haven't missed anything).  Just working on the last bit of the updated frontpage stats.

**Comment by dantheta** [comment]
5/6 frontpage stats are live.  One last query - which figure do we want to use for the suggested "“XXXX suspected mistakes identified by search” frontpage stat?

**Comment by JimKillock** [comment]
Thanks Dan

* Remove "Is your website being blocked?" - make "Get your site unblocked" the same as current size
* Put the right hand text and the form into the same grey block so they are clearly related.
* Move everything up a bit
* Reduce the gap between logo and the menu by about 50%
* Make the menu text a little big bigger
* In the block to the right, is this editable by us or do we need to give you new text?

**Comment by dantheta** [comment]
Title and gray block is done, spacing and menu adjusted.
The homepage text is resource 9778 in modx.

**Comment by JimKillock** [comment]
Re: "One last query - which figure do we want to use for the suggested "“XXXX suspected mistakes identified by search” frontpage stat?"

This can be a total of unique sites found in the saved lists.

**Comment by dantheta** [comment]
stats updated.

**Comment by JimKillock** [comment]
could you replace 
* "Why are websites being blocked in the UK?" 

with the text

* "Get your site unblocked by UK ISPs"

**Comment by dantheta** [comment]
I already had - the frontend cache needed clearing.  That's done now.

Logged-in admin users always see uncached content, so that it's getting the freshest text from modx.

**Comment by dantheta** [comment]
Closed, following on in #389
