### ISSUE TITLE
Holding page/url for Age Verification blocks

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#391]
Please add a page, along the lines of the Section 98 legal blocks, for sites blocked under the Digital Economy Act for non-compliance with the BBFC age-verification system.

Even if we don't have a mechanism to detect these when they occur, it would be good for people to see that a) it's something we intend to list b) we are unaware of any blocks so far.

**Comment by dantheta** [comment]
Added a link in the footer, and a ModX resource (10307) to contain the body text.

When we have a detection routine (or if court ordered blocks are added in the site database) we can list them here.

The DEA s.23 power is already setup in the backend.  We'd need to separate these out from the existing copyright block pages, but that's pretty straightforward to do.

**Comment by alexhaydock** [comment]
@gwire It's worth noting that although we might not be able to detect this programmatically, the BBFC intend to publish info about any enforcement action taken publicly on their site. [See 2.16](https://www.ageverificationregulator.com/assets/bbfc-guidance-on-age-verification-arrangements-october-2018-v2.pdf).

It's one thing I stressed very hard that they should do in the consultation response we wrote to them.

@JimKillock Perhaps ORG could try and push them in the direction of putting up such blocks in an easily-parseable format like JSON or something so the Blocked project can just import it regularly?

**Comment by gwire** [comment]
My suspicion is, as with how Section 97A orders have been publicised, the actions will be published but the actual technical information (e.g. the domain names being blocked) will not be.

**Comment by alexhaydock** [comment]
You may be right there. The consultation responses do indicate that they intend to use their website to _"report  the  results  of investigations and enforcement action"_ and that _"in  the  interests  of  transparency,  the BBFC will report all enforcement action on our website"_. So it looks like they do seem to be relatively interested in transparency, but it's a fair point that nothing they've published actually openly states that they'll be posting domain names publicly.
