### ISSUE TITLE
Exclude BT Strict only from front page / unblock recommendations

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#392]
It's not worth recommending user reviews for BT Strict blocks. Some of the sites are blocked by BT Strict only, so can we exclude these from the recommendations?

**Comment by JimKillock** [comment]
(see also #383 )

**Comment by dantheta** [comment]
These have been excluded now.  It makes the page load a bit slower, but we can add some caching tomorrow.

The number of frontpage random sites has gone from 138,000 to just under 10,000.

**Comment by dantheta** [comment]
Added the caching for blocked networks on items.  This speeds it up a lot.

Next up is the exclusions for category and keyword search follow-on suggestions.

**Comment by dantheta** [comment]
I think it could be worth coming back to the bt-strict exclusion on keyword & category search after #383 is done.  The "next URLs" and frontpage URL suggestions are provided by the same bit of code, and have the same pre-requisites (updating the search index).

**Comment by JimKillock** [comment]
i'm not sure this issue is resolved. For instance;

https://www.blocked.org.uk/unblock2?url=http://www.london-chauffeurs.co.uk 

was recommended to me off the front page

**Comment by dantheta** [comment]
Yep, I forgot to configure the feature when it was deployed.  That's 
done now.  Suggestions based on category or keyword search still need to 
have bt-strict excluded; that requires an update to the search index 
which will be done soon.
