### ISSUE TITLE
Tooltip to explain 'DNSError' status

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#395]
On a result page for a non-existent domain like [this here](https://www.blocked.org.uk/site/http://not-a-real-domain-aerg4rhafsd.com), we use "DNS Error" for the status.

Can we put a tooltip in to explain what that means?

If there's just a name for the status that is easier to understand and means we don't need a tooltip then that would be better.

**Comment by dantheta** [comment]
We could use "Site not found"?

The dnserror status represents a fairly broad category of DNS resolution errors.

**Comment by edjw** [comment]
Is a DNS Error status only ever shown when a site couldn't be found? Or are there other times when we could get DNS Error?

**Comment by JimKillock** [comment]
This example should fail at a 'whois' level? 

The DNS "error" is a correct result: the domain does not exist. Ideally, we would say that, to distinguish non existent domains from DNS and hosting set up issues.

**Comment by edjw** [comment]
So we can say "Non-existent domain" instead of "DNS Error" in those cases then?

**Comment by edjw** [comment]
@dantheta – Why does TalkTalk and BT Strict have a status of "OK" for that non-existent domain?

**Comment by leedxw** [comment]
I believe that some ISPs hijack NXDOMAIN DNS responses and return the IP address of an ISP-branded search portal.  (It should probably be a separate bug report to recognise these.)

**Comment by dantheta** [comment]
Yep, that's right.  Virgin and talktalk have used a service like barefruit in the past.  BT have their own, hosted on ttp://www.webaddresshelp.bt.com.

We turned it off on the A&A lines.

**Comment by dantheta** [comment]
> Is a DNS Error status only ever shown when a site couldn't be found? Or are there other times when we could get DNS Error?

We sometimes get SERVFAIL or REFUSED responses from an authoritative nameserver, in the absence of a cached record nearer to the probes.  They don't happen too often and tend to be temporary misconfigurations  or unavailable servers.

**Comment by edjw** [comment]
I'm not seeing the tooltip on the example page I gave originally
https://www.blocked.org.uk/site/http://not-a-real-domain-aerg4rhafsd.com
