### ISSUE TITLE
Re-write HTTPS warning message in block pages

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#396]
This is the banner message we present when someone requests an https URL. See a page like this one for an example: https://www.blocked.org.uk/site/https://theguardian.com

We should re-write it to make more sense to non-technical users.

> Parental control filter systems can have difficulty providing human readable responses for HTTPS requests, due to certificate errors.
>
> View the non-HTTPS results for this site.

**Comment by edjw** [comment]
@dantheta @JimKillock – How about something like this instead of the above?

>We can't get reliable results for web addresses starting with `https://`. [See accurate results for the `http://` version of this address]() instead.

**Comment by dantheta** [comment]
Looks good to me.

**Comment by dantheta** [comment]
I've added this here: https://www.blocked.org.uk/site/https://theguardian.com.

Should we add a FAQ entry with a more detailed explanation of why this happens (and that HTTPS highlights the ISP filter's interference)

**Comment by edjw** [comment]
Thanks Dan. There seems to be an empty <div class="row> above that message. Can you remove it from the template or make it conditional if something sometimes goes there?

Yes to the FAQ entry. Preferably with an anchor link to the entry. Then we can put some small text in a slightly less black colour at the bottom of the warning message that says "More info" which is linked to the FAQ entry

**Comment by dantheta** [comment]
I've removed the row, added a FAQ entry to modx resource 9783, and added a "more info" link pointing to it.  The text of the FAQ entry will definitely need revising.

**Comment by edjw** [comment]
Thanks Dan, the FAQ entry isn't showing up for me yet
