### ISSUE TITLE
Make copy of headings clearer on Site blocking report pages

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#400]
I showed Blocked to my wife earlier and this is something that confused her.

When you check a URL you get a Site blocking report. It was not clear to my wife which ISPs were blocking the URL and which weren't.

We're only relying on the background colour to communicate some of this. We should use better copy on the headings to help users with this.

I think changes like these would really help.

"Active blocks" -> "ISPs currently blocking this site"

"Past blocks" -> "ISPs who previously blocked this site"

"All results" -> "ISPs never detected as blocking this site" (This one needs improving a bit more but it's accurate, I think(?) The current label isn't accurate though. It's not **All** results!)

––––––

(I am almost certain that the background of the Active Blocks section does not actually turn green when you scroll. It might be worth checking though.)

![CleanShot 2019-06-07 at 14 38 54](https://user-images.githubusercontent.com/6547979/59108164-3873e400-8932-11e9-9019-071d80090823.gif)

**Comment by dantheta** [comment]
Yep, we can definitely change those.

I'm sure we used to have the text description of the status on each row 
for a degree of accessibility (I'm colorblind).

All results really meant "all other results"

> (I am almost certain that the background of the Active Blocks section
> does not actually turn green when you scroll. It might be worth
> checking though.)

Can you elaborate on this one?  As far as I can remember there aren't 
any scripted color changes, and the CSS background colors are applied 
statically.

**Comment by edjw** [comment]
> Can you elaborate on this one?

Those rows change colour on the attached gif. I'm not sure that it's accurate

**Comment by dantheta** [comment]
I've done an initial update of the titles.  In live results mode, the current and past updates are as suggested.  I've changed "all results" to "all other results" for now, but it's easy to change.

In non-live results mode, the current and past blocks use the format "_x_ past blocks" and "_x_ active blocks".  We can change these to match the longer form titles if you like.

**Comment by dantheta** [comment]
This has been rolled out now.  In live check mode, all three headings are always available, and the "All results" heading is now titled "All other results".  In non-live mode, the active and past blocks are only visible if there is an entry to be shown.  If there are current or past blocks, the "all results" heading is "all other results", otherwise it defaults to "all results".
