### ISSUE TITLE
Site returning a 500 error

### ISSUE THREAD

**Issue by ghost** [openrightsgroup/blocked-org-uk#403]
Hi,

I'm not sure if this is the right place as the site being down probably doesn't have anything to do with front end code but I wanted to check if anyone else is getting "500 Internal Server Error" when accessing https://www.blocked.org.uk?

Regards,
Jim

**Comment by JimKillock** [comment]
Thanks Jim, down for me too. @dantheta will take a look!

**Comment by dantheta** [comment]
That's fixed now - a database update filled the server with Wal.
