### ISSUE TITLE
Input on Check if site is blocked page is too wide

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#405]
![image](https://user-images.githubusercontent.com/6547979/104639355-3aba2a80-569f-11eb-8726-d707fefd6bae.jpeg)

**Comment by dantheta** [comment]
Hi Ed!

Can you tell me which browser and OS version you're using (and device model, if you're happy sharing that)?  I haven't been able to reproduce this on Chrome or Firefox on Android 9, but I'll check a couple of other devices.

**Comment by dantheta** [comment]
Actually, scratch that - I've found it on the /check page.  Thanks for letting us know!

**Comment by dantheta** [comment]
Thanks, that's fixed now!
