### ISSUE TITLE
Allow site submission from error page

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#417]
For lists of blocked domains (eg on the 451 wiki) I turn them into links that look like, for example

```
https://www.blocked.org.uk/results?url=http://www.example.com
```

In the event that `www.example.com` isn't in the testing database the site returns an Error page. It would be useful if the error page contained a "Check site" form with the domain pre-filled from the URL.

**Comment by dantheta** [comment]
Added a proper "no results" page, with a check site form.
