### ISSUE TITLE
Contact your MP action

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/blocked-org-uk#42]
Contact MP / take action stuff <- is there a page on ORG (or another site) where you enter your postcode and it gets your MP and a form to contact them like I've seen on some sites (38 degrees??) I think this would be good to make it easy to do. I've added in placeholder text for this on a couple of pages.

**Comment by JimKillock** [comment]
Ed, one for you to take up if you feel appropriate, or close.

**Comment by edjw** [comment]
https://www.blocked.org.uk/email-your-mp

Copy is still needed for the page

I made a new Template in ModX for this page 'Blocked Email your MP'. This template has a slightly different chunk in the head '$blocked_head_email_mp' to include scripts and css needed for the Campaignion email action

**Comment by JimKillock** [comment]
I suggest we close this for now?

**Comment by edjw** [comment]
I agree
