### ISSUE TITLE
No donation page/link

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#71]
There isn't a way for people to donate to the project on the site. There should be either a page where people can donate or a link to openrightsgroup.org/donate

**Comment by JimKillock** [comment]
There are links now but nothing much else. Simple fix, add "donate" to the top menu?

**Comment by pamcowburn** [comment]
Do we need copy for this?

**Comment by edjw** [comment]
I've added a link in the menu to openrightsgroup.org/donate Marking as closed
