### ISSUE TITLE
Category browser drill downs

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#72]
Reduce the amount of drilling down if possible, to the user gets a reasonable number of URLs to check without too many clicks.

This could be an option: eg "View all sites listed within this category" which is made available when the number of sites is less than 30.

https://github.com/openrightsgroup/cmp-issues/issues/158

**Comment by dantheta** [comment]
The site now searches lower in the hierarchy when the number of blocks beneath a category is < 1000.  (this cutoff is mainly to preserve preserve performance).

In practice, this means the user only needs to click down 3 categories before typically finding sites.

We can apply paging for the list of sites contained within a category, but for the moment it is limited to 20.

**Comment by dantheta** [comment]
Also, beneath each URL in the site list is a link to the category that the URL is found in, making it easier to jump down to a sublevel which is rich in blocks.

**Comment by JimKillock** [comment]
This is looking good - @pamcowburn can you take a look?

**Comment by pamcowburn** [comment]
Is it possible to link to the URL and the blocked results - at minute linking just to results so have to paste separately to check site is ok

**Comment by dantheta** [comment]
The icon that is a square with an arrow pointing out of it will open the 
original site in a new tab/window.  The function of those three icons 
isn't really clear enough, even with tooltips.  I can replace them with 
a dropdown menu button, which would at least describe what they do in 
text.

**Comment by pamcowburn** [comment]
Not sure if this needs separate ticket but could we re-order the top subcategories - alphabetically would work. The two top categories Regional and World have the highest number of sites and require more drilling down.  I think better if they were lower down list.

**Comment by dantheta** [comment]
The sort ordering is done - the very top level is alphabetically sorted, and lower levels are sorted by block count descending.

**Comment by dantheta** [comment]
Are we happy with the three function icons (+tooltips) on  the site list, or do we want to look at an alternative action-menu-type-thing?

**Comment by JimKillock** [comment]
For me tool tips is ok but lack of prominence / size is an issue. Also the link to the blocked is counter intuitive currently as it appears as a link to the URK itself

**Comment by pamcowburn** [comment]
Yes - I think it would make sense for the URL to link to the site itself so first thing people are doing is looking at whether the site should be blocked or not

**Comment by dantheta** [comment]
That's a very good point.  I've switched those two around.  I've also made them a bit larger.

**Comment by dantheta** [comment]
The category tree is about 75% faster now (although a tiny bit slower the very first time a 2nd-level category is accessed).  There are now two levels of cache, and a much, much faster tree implementation.

**Comment by JimKillock** [comment]
great :)
