### ISSUE TITLE
Show reported site details in frontend

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#82]
Re: second paragraph of #75

**Comment by dantheta** [comment]
> This information can be displayed on the links within the browser, eg "This website appears to be sqautted and is likely to be blocked legitimately."

**Comment by dantheta** [comment]
This is done now.  When viewing a flagged site, the "Tell us about this site" cell contains some information about flags that have already been applied to that site.

**Comment by JimKillock** [comment]
Could you send a link to a flagged site to show us how it looks? The information should be reasonably prominent to someone looking at the page.

**Comment by dantheta** [comment]
https://www.blocked.org.uk/site/http://www.nottsgirls.co.uk
