### ISSUE TITLE
Index-able results pages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#86]
Generate results pages and sitemap so pages can be picked up by Google / Bing / DDG

**Comment by dantheta** [comment]
This might be a tricky one - site crawlers are quite prejudiced against query-string style URLs.  We can try changing the URL format so that it is search-engine friendly, but I don't know if modx will play along.

**Comment by dantheta** [comment]
Converted category site listings to server-side generated pages, with crawl-friendly links (and rel=nofollow on external links)
