### ISSUE TITLE
Pages requiring copy

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#92]
* "100,000 most popular sites", linked from front page
* FAQ
* "By internet service provider", linked from front page
* Personal Stories
* Donate

**Comment by dantheta** [comment]
If we're intending to copy these from the existing site, I'm happy to take care of it.  Let me know if you'd like me to get them copied.

**Comment by JimKillock** [comment]
Yes, I think we should move this content. I think only the 'personal stories' is currently missing.

**Comment by dantheta** [comment]
That one has been ported. It's linked from the footer.

On 13 October 2017 08:56:43 BST, JimKillock <notifications@github.com> wrote:
>Yes, I think we should move this content. I think only the 'personal
>stories' is currently missing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/blocked-org-uk/issues/92#issuecomment-336379177

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
