### ISSUE TITLE
Homepage "Get a site unblocked" link

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/blocked-org-uk#95]
On the homepage, there is a link entitled "Get a site unblocked".  Where should this link point to? "Check if a site is being blocked" points to the URL lookup form, and it seems that the "Get a site unblocked" link would go to the same place.

**Comment by JimKillock** [comment]
Agreed,  it is the same thing, but different motivations I guess?

**Comment by dantheta** [comment]
Yes, I think so.  They take on a bigger distinction if one link goes to live checking of the site and the other goes to historical results without re-testing; I'm not sure that's a distinction that the user is very concerned about though.

I'll point the "Get a site unblocked" link at the check form for now.
