### ISSUE TITLE
Bug on autocomplete of placenames

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#98]
I am finding that some locations, eg Manchester, Birmingham aren't correctly autocompleting in the category browsers

**Comment by dantheta** [comment]
I'm finding that Manchester and Birmingham appear at 4 characters ("manc" and "birm" respectively).  For a given input string, the dropdown shows the 10 most blocked categories starting with that string.  

Increasing the number of results in the dropdown gets Manchester to appear at number 18.  Birmingham appears at number 23.

I've set it to 20, although there is a slight corresponding performance decrease.

**Comment by JimKillock** [comment]
Great - yes this seems to be working. Not sure if that was fixed or a temporary glitch
